import * as THREE from 'three';
import {canReachPosition,distance,isActive,isBlockedTerrain,type BattleState,type DamageKind,type Position,type SkillId,type TerrainCell,type Unit} from '../game/battle';
import {attackAction,CharacterVisualLoader,deathAction,hitAction,type CharacterVisualInstance,type VisualAction} from './characterVisuals';
import {CharacterIllustrationLoader} from './characterIllustrations';
import {EnvironmentVisualLoader} from './environmentVisuals';
import {defaultBattlePalette} from './battleScenePresets';
import {appendVeiledSanctumDetails} from './veiledSanctumProps';
import {deathBurst, faithBurst, healthImpact, healthSlash, moveDust, skillPulse} from './battleFxTemplates';
import type {BattleScenePreset} from './battleScenePresets';
export type BattleInput=
 | {type:'select';unitId:string}
 | {type:'inspect';unitId:string}
 | {type:'cancel'}
 | {type:'move';unitId:string;destination:Position}
 | {type:'attack';unitId:string;targetId:string;damageKind:DamageKind}
 | {type:'skill';unitId:string;targetId:string;skill:SkillId}
 | {type:'terrain';position:Position;kind:TerrainCell['kind']};
export type BattleAnimation=
 | {type:'move';unitId:string;from:Position;to:Position}
 | {type:'attack';unitId:string;targetId:string;damageKind:DamageKind;amount:number;visualAction?:VisualAction;affectedTargetIds?:string[];critical?:boolean}
 | {type:'skill';unitId:string;targetId:string;skill:SkillId};
const GRID=8,C={p:0x3497ad,pd:0x1d5667,e:0xb94e52,ed:0x642d35,gold:0xc69a52,steel:0xa5b5bc,skin:0xd8a080,leather:0x5b3b30};
export class Battlefield{
 private terrainPickables:THREE.Object3D[]=[];private terrainMeshes:THREE.Object3D[]=[];private environmentLoader=new EnvironmentVisualLoader();
 private scene=new THREE.Scene();private camera:THREE.OrthographicCamera;private renderer:THREE.WebGLRenderer;private ray=new THREE.Raycaster();private pointer=new THREE.Vector2();private groundPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);private cameraTarget=new THREE.Vector3(3.5,.35,3.5);private cameraOffset=new THREE.Vector3(7.3,12.15,8.3);private resizeObserver?:ResizeObserver;private drag?:{pointerId:number;world:THREE.Vector3;startX:number;startY:number;moved:boolean};private activePointers=new Map<number,{x:number;y:number}>();private pinch?:{distance:number;zoom:number};private consumedPointerIds=new Set<number>();private unitMeshes=new Map<string,THREE.Group>();private unitPickables:THREE.Object3D[]=[];private boardPickables:THREE.Object3D[]=[];private visualLoader=new CharacterVisualLoader();private illustrationLoader=new CharacterIllustrationLoader();private visuals=new Map<string,CharacterVisualInstance>();private selectedId?:string;private attackMode?:DamageKind;private inputLocked=false;private running=true;private ring?:THREE.Mesh;private flame?:THREE.Group;private dust?:THREE.Points;private clock=new THREE.Clock();private lastFrame=0;private overlays:THREE.Mesh[]=[];private attackRangeOverlays:THREE.Mesh[]=[];private targetOverlays:THREE.Mesh[]=[];private intentOverlays:THREE.Mesh[]=[];private flashOverlays:THREE.Mesh[]=[];private reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 private backgroundTexture?:THREE.Texture;
 private cameraRotation=0;
 private pinchAngle=0;
 constructor(private host:HTMLElement,private state:BattleState,private emit:(e:BattleInput)=>void,private scenePreset?:BattleScenePreset){
  this.buildTerrain();
  const lighting=this.scenePreset?.lighting;this.scene.background=new THREE.Color(lighting?.background??0x18242d);this.scene.fog=new THREE.Fog(lighting?.fog??0x18242d,10.5,21);const a=Math.max(.65,host.clientWidth/Math.max(1,host.clientHeight)),s=12.8;this.camera=new THREE.OrthographicCamera(-s*a/2,s*a/2,s/2,-s/2,.1,100);this.syncCamera();
  this.renderer=new THREE.WebGLRenderer({antialias:devicePixelRatio<2,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(host.clientWidth,host.clientHeight);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=lighting?.exposure??1.08;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.append(this.renderer.domElement);this.build();this.resize();this.renderer.domElement.addEventListener('pointerdown',this.onPointerDown);this.renderer.domElement.addEventListener('pointerup',this.onPointerUp);this.renderer.domElement.addEventListener('pointercancel',this.onPointerCancel);this.renderer.domElement.addEventListener('pointermove',this.onPointerMove);if(typeof ResizeObserver!=='undefined'){this.resizeObserver=new ResizeObserver(this.resize);this.resizeObserver.observe(host)}addEventListener('resize',this.resize);this.loop();
 }
 private mat(color:number,roughness=.82,metalness=0){return new THREE.MeshStandardMaterial({color,roughness,metalness,flatShading:true})}
 private make(geo:THREE.BufferGeometry,mat:THREE.Material,cast=true){const o=new THREE.Mesh(geo,mat);o.castShadow=cast;o.receiveShadow=true;return o}
 private addSceneBackground(){const url=this.scenePreset?.background;if(!url)return;new THREE.TextureLoader().load(url,texture=>{if(!this.running){texture.dispose();return}texture.colorSpace=THREE.SRGBColorSpace;this.scene.background=texture;this.backgroundTexture=texture},undefined,()=>undefined)}
 private buildTerrain(){const palette=this.scenePreset?.palette??defaultBattlePalette;for(const cell of this.state.terrain){const color=palette.terrain[cell.kind];const group=new THREE.Group();group.userData.terrain=cell;const base=this.make(new THREE.BoxGeometry(.78,.08,.78),this.mat(color,.95),false);base.position.y=.01;base.userData.terrain=cell;group.add(base);if(cell.kind==='holy-fire'){const flame=this.make(new THREE.ConeGeometry(.16,.46,6),new THREE.MeshBasicMaterial({color:palette.flame,transparent:true,opacity:.8}),false);flame.position.y=.3;flame.userData.terrain=cell;group.add(flame)}else if(cell.kind==='ruin-cover'){const wall=this.make(new THREE.BoxGeometry(.7,.55,.18),this.mat(color,.9),true);wall.position.y=.3;wall.rotation.y=(cell.position.x+cell.position.y)%2?.18:-.18;wall.userData.terrain=cell;group.add(wall)}else if(cell.kind==='brush'){const bush=this.make(new THREE.DodecahedronGeometry(.28,0),this.mat(color,.96),true);bush.scale.y=.7;bush.position.y=.25;bush.userData.terrain=cell;group.add(bush)}else if(cell.kind==='mechanism'){const ring=this.make(new THREE.TorusGeometry(.25,.06,5,8),this.mat(color,.45,.65),false);ring.rotation.x=Math.PI/2;ring.position.y=.12;ring.userData.terrain=cell;group.add(ring)}appendVeiledSanctumDetails(group,cell);group.traverse(child=>child.userData.terrain=cell);const visual=this.environmentLoader.create(cell,group,color);visual.position.set(cell.position.x,0,cell.position.y);visual.userData.terrain=cell;this.scene.add(visual);this.terrainMeshes.push(visual);this.terrainPickables.push(visual)}}
 private build(){
  const lighting=this.scenePreset?.lighting;this.scene.add(new THREE.HemisphereLight(0xb9d8e3,0x273039,1.12));const sun=new THREE.DirectionalLight(0xffd8ad,lighting?.sun??2.75);sun.position.set(-5,11,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-7;sun.shadow.camera.right=7;sun.shadow.camera.top=7;sun.shadow.camera.bottom=-7;sun.shadow.bias=-.001;this.scene.add(sun);const fill=new THREE.DirectionalLight(0x89b9d0,lighting?.fill??.72);fill.position.set(8,8,10);this.scene.add(fill);const rim=new THREE.DirectionalLight(0x6d9ac4,lighting?.rim??.9);rim.position.set(10,6,-8);this.scene.add(rim);
  const palette=this.scenePreset?.palette??defaultBattlePalette;this.addSceneBackground();const slab=this.make(new THREE.BoxGeometry(9.15,.48,9.15),this.mat(palette.slab),false);slab.position.set(3.5,-.43,3.5);this.scene.add(slab);const geo=new THREE.BoxGeometry(.94,.18,.94),tiles=new THREE.InstancedMesh(geo,this.mat(0xffffff,.96),64);tiles.receiveShadow=true;tiles.userData.board=true;this.boardPickables.push(tiles);const m=new THREE.Matrix4();let n=0;for(let z=0;z<8;z++)for(let x=0;x<8;x++){m.makeRotationY((((x*11+z*5)%3)-1)*.008);m.setPosition(x,-.11+((x*7+z*3)%5)*.004,z);tiles.setMatrixAt(n,m);tiles.setColorAt(n++,new THREE.Color((x+z)%2?palette.tileOdd:palette.tileEven).offsetHSL(0,0,((x*13+z*17)%7-3)*.012))}tiles.instanceColor!.needsUpdate=true;this.scene.add(tiles);this.frame();this.altar();this.atmosphere();this.state.units.forEach(u=>this.addUnit(u));this.ring=this.make(new THREE.RingGeometry(.39,.52,32),new THREE.MeshBasicMaterial({color:0x8aebf5,transparent:true,opacity:.92,depthWrite:false,depthTest:false}),false);this.ring.rotation.x=-Math.PI/2;this.ring.position.y=.095;this.ring.visible=false;this.scene.add(this.ring);this.sync(this.state);
 }
 private frame(){const palette=this.scenePreset?.palette??defaultBattlePalette,wall=this.mat(palette.frame,.95),cap=this.mat(palette.cap,.86),gx=new THREE.BoxGeometry(9,.44,.25),gz=new THREE.BoxGeometry(.25,.44,9);for(const p of [[3.5,-.08,-.62],[3.5,-.08,7.62]]){const o=this.make(gx,wall);o.position.set(...p as [number,number,number]);this.scene.add(o)}for(const p of [[-.62,-.08,3.5],[7.62,-.08,3.5]]){const o=this.make(gz,wall);o.position.set(...p as [number,number,number]);this.scene.add(o)}for(const [x,z] of [[-.62,-.62],[7.62,-.62],[-.62,7.62],[7.62,7.62]]){const p=this.make(new THREE.CylinderGeometry(.27,.34,.68,6),cap);p.position.set(x,.12,z);this.scene.add(p);const b=this.make(new THREE.CylinderGeometry(.18,.12,.2,8),this.mat(palette.gold,.45,.55));b.position.set(x,.56,z);this.scene.add(b);const l=new THREE.PointLight(palette.glow,.65,2.5,2);l.position.set(x,.83,z);this.scene.add(l)}const rg=new THREE.DodecahedronGeometry(.18,0);for(const [x,z,r] of [[.1,2.6,.3],[7.05,5.8,1.1],[4.8,7.05,.7]]){const o=this.make(rg,wall);o.scale.set(1.5,.55,1);o.position.set(x,.08,z);o.rotation.y=r;this.scene.add(o)}}
 private altar(){const palette=this.scenePreset?.palette??defaultBattlePalette,g=new THREE.Group();g.position.set(3.5,0,3.5);const stone=this.mat(palette.ground,.9),gold=this.mat(palette.gold,.38,.62);for(const [geo,y] of [[new THREE.CylinderGeometry(.78,.9,.24,8),.11],[new THREE.CylinderGeometry(.57,.7,.24,8),.33],[new THREE.CylinderGeometry(.34,.45,.82,8),.79]] as [THREE.BufferGeometry,number][]){const o=this.make(geo,stone);o.position.y=y;g.add(o)}const band=this.make(new THREE.TorusGeometry(.37,.055,5,8),gold);band.rotation.x=Math.PI/2;band.position.y=1.02;g.add(band);const bowl=this.make(new THREE.CylinderGeometry(.4,.25,.18,8),this.mat(palette.frame,1));bowl.position.y=1.26;g.add(bowl);this.flame=new THREE.Group();this.flame.position.y=1.47;const outer=this.make(new THREE.ConeGeometry(.2,.72,7),new THREE.MeshBasicMaterial({color:palette.flame,transparent:true,opacity:.76}),false);outer.position.y=.22;const inner=this.make(new THREE.ConeGeometry(.1,.46,6),new THREE.MeshBasicMaterial({color:palette.glow}),false);inner.position.y=.16;this.flame.add(outer,inner);g.add(this.flame);const glow=new THREE.PointLight(palette.glow,2.8,5,2);glow.position.y=1.75;g.add(glow);this.scene.add(g)}
 private atmosphere(){const p=new Float32Array(216);for(let i=0;i<72;i++){p[i*3]=Math.random()*10-1.5;p[i*3+1]=Math.random()*3.2+.2;p[i*3+2]=Math.random()*10-1.5}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(p,3));this.dust=new THREE.Points(geo,new THREE.PointsMaterial({color:0xd8b76e,size:.035,transparent:true,opacity:.45,depthWrite:false}));this.scene.add(this.dust)}
 private addUnit(u:Unit){const fallback=this.unitModel(u),visual=this.illustrationLoader.create(u,fallback)??this.visualLoader.create(u,fallback),g=visual.root;g.userData.unitId=u.id;g.position.set(u.position.x,0,u.position.y);g.rotation.y=u.team==='player'?Math.PI:0;this.scene.add(g);this.unitMeshes.set(u.id,g);this.unitPickables.push(visual.hitTarget);this.visuals.set(u.id,visual)}
 private unitModel(u:Unit){
  const g=new THREE.Group(),player=u.team==='player',elite=u.id==='u1'||u.id==='e1',priest=u.id==='u2'||u.id==='e2',main=this.mat(player?C.p:C.e,.72,.08),dark=this.mat(player?C.pd:C.ed,.9),cloth=this.mat(player?0xb9d5d7:0xd1b7a4,.96),metal=this.mat(elite?C.steel:C.gold,.35,.7),skin=this.mat(C.skin,.9),leather=this.mat(C.leather,.95);
  const legGeo=new THREE.BoxGeometry(.14,.42,.16);for(const x of [-.13,.13]){const leg=this.make(legGeo,dark);leg.position.set(x,.28,0);g.add(leg);const boot=this.make(new THREE.BoxGeometry(.17,.15,.24),leather);boot.position.set(x,.09,.035);g.add(boot)}const torso=this.make(new THREE.CylinderGeometry(.24,.31,.58,6),main);torso.position.y=.72;torso.scale.z=.72;g.add(torso);const belt=this.make(new THREE.CylinderGeometry(.29,.29,.09,8),leather);belt.position.y=.49;belt.scale.z=.73;g.add(belt);const skirt=this.make(new THREE.CylinderGeometry(.25,.37,.38,6,1,true),cloth);skirt.position.set(0,.41,.04);skirt.scale.z=.7;g.add(skirt);const cape=this.make(new THREE.PlaneGeometry(.48,.67),dark);cape.position.set(0,.69,.19);cape.rotation.x=-.13;g.add(cape);const head=this.make(new THREE.SphereGeometry(.18,8,6),skin);head.position.y=1.19;head.scale.set(.88,1.05,.88);g.add(head);
  if(elite){const helm=this.make(new THREE.SphereGeometry(.205,8,5,0,Math.PI*2,0,Math.PI*.62),metal);helm.position.y=1.22;g.add(helm);const nose=this.make(new THREE.BoxGeometry(.045,.2,.04),metal);nose.position.set(0,1.18,-.17);g.add(nose);for(const x of [-.31,.31]){const s=this.make(new THREE.SphereGeometry(.15,7,4),metal);s.scale.set(1.2,.55,.9);s.position.set(x,.9,0);g.add(s)}}else if(priest){const hood=this.make(new THREE.ConeGeometry(.26,.42,7,1,true),dark);hood.position.y=1.25;g.add(hood);const sash=this.make(new THREE.BoxGeometry(.09,.55,.025),this.mat(C.gold,.5,.25));sash.position.set(-.07,.72,-.23);sash.rotation.z=-.12;g.add(sash)}else{const cap=this.make(new THREE.CylinderGeometry(.19,.22,.18,7),metal);cap.position.y=1.29;g.add(cap)}
  const armGeo=new THREE.CylinderGeometry(.075,.09,.5,6);for(const x of [-.3,.3]){const arm=this.make(armGeo,main);arm.position.set(x,.72,0);arm.rotation.z=x<0?-.12:.12;g.add(arm)}if(priest){const staff=this.make(new THREE.CylinderGeometry(.025,.035,1.18,6),leather);staff.position.set(.39,.63,-.04);g.add(staff);const halo=this.make(new THREE.TorusGeometry(.12,.025,5,8),metal);halo.position.set(.39,1.22,-.04);halo.rotation.x=Math.PI/2;g.add(halo)}else{const shield=this.make(new THREE.CylinderGeometry(.25,.25,.08,8),main);shield.rotation.z=Math.PI/2;shield.position.set(-.4,.7,-.03);g.add(shield);const boss=this.make(new THREE.SphereGeometry(.08,7,4),metal);boss.position.set(-.45,.7,-.03);g.add(boss);const sword=this.make(new THREE.BoxGeometry(.06,.66,.035),metal);sword.position.set(.4,.72,-.03);sword.rotation.z=-.13;g.add(sword)}const base=this.make(new THREE.CylinderGeometry(.34,.38,.09,16),this.mat(player?0x244f60:0x59262b,.7,.15));base.position.y=.025;g.add(base);return g;
 }
 private pointerHits(ev:PointerEvent){const r=this.renderer.domElement.getBoundingClientRect();if(!r.width||!r.height)return[];this.pointer.set((ev.clientX-r.left)/r.width*2-1,-((ev.clientY-r.top)/r.height*2-1));this.ray.setFromCamera(this.pointer,this.camera);const unitHits=this.ray.intersectObjects(this.unitPickables,false);const boardHits=this.ray.intersectObjects([...this.boardPickables,...this.overlays,...this.terrainPickables],true);return[...unitHits,...boardHits]}
 private worldFromPointer(ev:PointerEvent){return this.worldFromClient(ev.clientX,ev.clientY)}
 private worldFromClient(clientX:number,clientY:number){const r=this.renderer.domElement.getBoundingClientRect();if(!r.width||!r.height)return;this.pointer.set((clientX-r.left)/r.width*2-1,-((clientY-r.top)/r.height*2-1));this.ray.setFromCamera(this.pointer,this.camera);return this.ray.ray.intersectPlane(this.groundPlane,new THREE.Vector3())??undefined}
 private boardPosition(hits:THREE.Intersection[]):Position|undefined{const hit=hits.find(item=>item.object.userData.board||item.object.userData.cell);if(!hit)return;return{x:Math.round(hit.point.x),y:Math.round(hit.point.z)}}
 private onPointerDown=(ev:PointerEvent)=>{this.activePointers.set(ev.pointerId,{x:ev.clientX,y:ev.clientY});this.renderer.domElement.setPointerCapture?.(ev.pointerId);if(this.activePointers.size===2){const pointers=[...this.activePointers.entries()],first=pointers[0][1],second=pointers[1][1];this.pinch={distance:Math.hypot(first.x-second.x,first.y-second.y),zoom:this.camera.zoom};this.pinchAngle=Math.atan2(first.y-second.y,first.x-second.x);this.drag=undefined;this.consumedPointerIds.add(pointers[0][0]);this.consumedPointerIds.add(pointers[1][0]);return}if(!ev.isPrimary)return;const world=this.worldFromPointer(ev);if(!world)return;this.drag={pointerId:ev.pointerId,world,startX:ev.clientX,startY:ev.clientY,moved:false};this.renderer.domElement.style.cursor='grabbing'}
 private onPointerUp=(ev:PointerEvent)=>{const drag=this.drag,consumed=this.consumedPointerIds.delete(ev.pointerId);this.activePointers.delete(ev.pointerId);this.renderer.domElement.releasePointerCapture?.(ev.pointerId);if(this.pinch&&this.activePointers.size<2)this.pinch=undefined;if(drag?.pointerId===ev.pointerId)this.drag=undefined;if(!this.activePointers.size)this.renderer.domElement.style.cursor='default';if(consumed||drag?.moved)return;this.onPointer(ev)}
 private onPointerCancel=(ev:PointerEvent)=>{this.activePointers.delete(ev.pointerId);this.consumedPointerIds.delete(ev.pointerId);if(this.drag?.pointerId===ev.pointerId)this.drag=undefined;if(this.activePointers.size<2)this.pinch=undefined;this.renderer.domElement.releasePointerCapture?.(ev.pointerId);if(!this.activePointers.size)this.renderer.domElement.style.cursor='default'}
 private onPointer=(ev:PointerEvent)=>{if(this.state.phase!=='player'||this.inputLocked)return;const hits=this.pointerHits(ev),id=hits.map(h=>h.object.userData.unitId).find(Boolean) as string|undefined,u=this.state.units.find(v=>v.id===id);if(u&&isActive(u)){if(u.team==='player'){if(this.selectedId===u.id){this.clearSelection();this.emit({type:'cancel'})}else if(!u.acted){this.select(u)}return}const selected=this.selected();if(selected&&this.attackMode&&distance(selected.position,u.position)<=selected.attackRange){this.emit({type:'attack',unitId:selected.id,targetId:u.id,damageKind:this.attackMode});return}this.clearSelection();this.emit({type:'inspect',unitId:u.id});return}const terrain=hits.map(h=>h.object.userData.terrain as TerrainCell|undefined).find(Boolean),destination=this.boardPosition(hits),selected=this.selected();if(terrain?.interactable&&selected&&distance(selected.position,terrain.position)<=1){this.emit({type:'terrain',position:terrain.position,kind:terrain.kind});return}if(selected&&!this.attackMode&&destination&&this.reachable(selected,destination))this.emit({type:'move',unitId:selected.id,destination})};
 private onPointerMove=(ev:PointerEvent)=>{if(this.activePointers.has(ev.pointerId))this.activePointers.set(ev.pointerId,{x:ev.clientX,y:ev.clientY});if(this.pinch&&this.activePointers.size>=2){const points=[...this.activePointers.values()],distance=Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y),angle=Math.atan2(points[0].y-points[1].y,points[0].x-points[1].x),delta=Math.atan2(Math.sin(angle-this.pinchAngle),Math.cos(angle-this.pinchAngle));this.cameraRotation+=delta;this.pinchAngle=angle;if(distance>0)this.setCameraZoom(this.pinch.zoom*distance/this.pinch.distance);return}const drag=this.drag;if(drag?.pointerId===ev.pointerId){if(!drag.moved&&Math.hypot(ev.clientX-drag.startX,ev.clientY-drag.startY)<7)return;const world=this.worldFromPointer(ev);if(world){drag.moved=true;const delta=drag.world.clone().sub(world);this.panCamera(delta);drag.world.copy(world)}this.renderer.domElement.style.cursor='grabbing';return}if(this.inputLocked){this.renderer.domElement.style.cursor='wait';return}const hits=this.pointerHits(ev),id=hits.map(h=>h.object.userData.unitId).find(Boolean) as string|undefined,pos=this.boardPosition(hits),terrain=hits.map(h=>h.object.userData.terrain as TerrainCell|undefined).find(Boolean),unit=this.state.units.find(v=>v.id===id&&isActive(v)),selected=this.selected();this.renderer.domElement.style.cursor=terrain?.interactable&&selected&&distance(selected.position,terrain.position)<=1||unit&&(unit.team==='player'&&!unit.acted||selected&&this.attackMode&&unit.team==='enemy'&&distance(selected.position,unit.position)<=selected.attackRange)||selected&&!this.attackMode&&pos&&this.reachable(selected,pos)?'pointer':'default';for(const overlay of this.overlays){const p=overlay.userData.position as Position;const mat=overlay.material as THREE.MeshBasicMaterial;mat.opacity=pos&&p.x===pos.x&&p.y===pos.y?.88:.62}}
 private selected(){return this.state.units.find(u=>u.id===this.selectedId&&isActive(u))}
 private reachable(unit:Unit,p:Position){return distance(unit.position,p)>0&&!isBlockedTerrain(this.state,p)&&!this.state.units.some(other=>isActive(other)&&other.position.x===p.x&&other.position.y===p.y)&&canReachPosition(this.state,unit.id,p)}
 private select(u:Unit){this.selectedId=u.id;this.emit({type:'select',unitId:u.id});this.drawOverlays();this.syncSelection()}
 private clearSelection(){this.selectedId=undefined;this.attackMode=undefined;this.drawOverlays();this.drawTargets();this.syncSelection()}
 private syncSelection(){this.syncTerrain();const selected=this.selected();this.unitMeshes.forEach((g,id)=>{const unit=this.state.units.find(u=>u.id===id);g.scale.setScalar(id===this.selectedId?1.07:unit?.acted?0.94:1)});if(this.ring){this.ring.visible=Boolean(selected);if(selected)this.ring.position.set(selected.position.x,.095,selected.position.y)}}
 private syncTerrain(){for(const mesh of this.terrainMeshes){const source=mesh.userData.terrain as TerrainCell|undefined;const current=source&&this.state.terrain.find(cell=>cell.position.x===source.position.x&&cell.position.y===source.position.y);mesh.visible=current?.active!==false}}
 private clearOverlayMeshes(list:THREE.Mesh[]){for(const mesh of list){this.scene.remove(mesh);mesh.geometry.dispose();(mesh.material as THREE.Material).dispose()}list.length=0}
 private drawAttackRange(selected:Unit){for(let y=0;y<GRID;y++)for(let x=0;x<GRID;x++){const p={x,y};if(distance(selected.position,p)===0||distance(selected.position,p)>selected.attackRange)continue;const mesh=this.make(new THREE.PlaneGeometry(.86,.86),new THREE.MeshBasicMaterial({color:0xf3cf58,transparent:true,opacity:.2,depthWrite:false,depthTest:false}),false);mesh.rotation.x=-Math.PI/2;mesh.position.set(x,.09,y);mesh.userData.position=p;this.scene.add(mesh);this.attackRangeOverlays.push(mesh)}}
 private drawOverlays(){this.clearOverlayMeshes(this.overlays);this.clearOverlayMeshes(this.attackRangeOverlays);const selected=this.selected();if(!selected)return;if(selected.team==='enemy'||this.attackMode){this.drawAttackRange(selected);return}for(let y=0;y<GRID;y++)for(let x=0;x<GRID;x++){const p={x,y};if(!this.reachable(selected,p))continue;const mesh=this.make(new THREE.PlaneGeometry(.84,.84),new THREE.MeshBasicMaterial({color:0x72e4f3,transparent:true,opacity:.62,depthWrite:false,depthTest:false}),false);mesh.rotation.x=-Math.PI/2;mesh.position.set(x,.085,y);mesh.userData.cell=true;mesh.userData.position=p;this.scene.add(mesh);this.overlays.push(mesh)}}
 private drawTargets(){this.clearOverlayMeshes(this.targetOverlays);const selected=this.selected();if(!selected||selected.team!=='player'||!this.attackMode)return;const color=this.attackMode==='health'?0xef5b55:0xf1d58c;for(const target of this.state.units.filter(unit=>unit.team==='enemy'&&isActive(unit)&&distance(selected.position,unit.position)<=selected.attackRange)){const marker=this.make(new THREE.RingGeometry(.42,.56,24),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9,depthWrite:false,depthTest:false}),false);marker.rotation.x=-Math.PI/2;marker.position.set(target.position.x,.095,target.position.y);marker.userData.unitId=target.id;this.scene.add(marker);this.targetOverlays.push(marker)}}
 private drawIntents(){for(const mesh of this.intentOverlays){this.scene.remove(mesh);mesh.geometry.dispose();(mesh.material as THREE.Material).dispose()}this.intentOverlays=[];for(const intent of this.state.enemyIntents){const position=intent.type==='move'?intent.destination:this.state.units.find(unit=>unit.id===intent.targetId)?.position;if(!position)continue;const marker=this.make(new THREE.PlaneGeometry(.86,.86),new THREE.MeshBasicMaterial({color:0xf0444f,transparent:true,opacity:.52,depthWrite:false,depthTest:false}),false);marker.rotation.x=-Math.PI/2;marker.position.set(position.x,.085,position.y);marker.userData.intent=true;marker.userData.intentUnitId=intent.unitId;this.scene.add(marker);this.intentOverlays.push(marker)}}
 flashCell(x:number,y:number){const marker=this.make(new THREE.RingGeometry(.2,.47,8),new THREE.MeshBasicMaterial({color:0xffe0a0,transparent:true,opacity:1,depthWrite:false}),false);marker.rotation.x=-Math.PI/2;marker.position.set(x,.065,y);this.scene.add(marker);this.flashOverlays.push(marker);const remove=()=>{this.scene.remove(marker);marker.geometry.dispose();(marker.material as THREE.Material).dispose();this.flashOverlays=this.flashOverlays.filter(item=>item!==marker)};if(this.reduced){setTimeout(remove,520);return}this.tween(520,t=>{marker.scale.setScalar(1+t*.7);(marker.material as THREE.MeshBasicMaterial).opacity=1-t},remove)}
 setAttackMode(mode?:DamageKind){if(this.inputLocked&&mode)return;this.attackMode=mode;this.drawOverlays();this.drawTargets()}
 getAttackMode(){return this.attackMode}
 isBusy(){return this.inputLocked}
 sync(state:BattleState,animation?:BattleAnimation){const previous=this.state;this.state=state;const selected=this.selected();if(this.selectedId&&(!selected||selected.acted||state.phase!=='player'))this.selectedId=undefined;const newlyInactive=state.units.filter(unit=>!isActive(unit)&&isActive(previous.units.find(old=>old.id===unit.id)??unit));const animatedIds=new Set(animation?.type==='move'?[animation.unitId]:animation?.type==='attack'?[animation.unitId,...(animation.affectedTargetIds??[animation.targetId])]:animation?.type==='skill'?[animation.unitId,animation.targetId]:newlyInactive.map(unit=>unit.id));for(const unit of state.units){const mesh=this.unitMeshes.get(unit.id);if(!mesh)continue;if(!animatedIds.has(unit.id))mesh.position.set(unit.position.x,0,unit.position.y);if(!animatedIds.has(unit.id))mesh.visible=isActive(unit);mesh.userData.active=isActive(unit)}this.drawOverlays();this.drawTargets();this.drawIntents();this.syncSelection();if(this.reduced){for(const unit of state.units){const mesh=this.unitMeshes.get(unit.id);if(mesh){mesh.position.set(unit.position.x,0,unit.position.y);mesh.visible=isActive(unit)}}return}if(animation){this.inputLocked=true;if(animation.type==='move')this.animateMove(animation,state);else if(animation.type==='attack')this.animateAttack(animation,state,previous);else this.animateSkill(animation,state);return}if(newlyInactive.length){this.animateDefeats(newlyInactive,state);return}for(const unit of state.units){const mesh=this.unitMeshes.get(unit.id);if(mesh){mesh.position.set(unit.position.x,0,unit.position.y);mesh.visible=isActive(unit)}}}
 private animateMove(animation:Extract<BattleAnimation,{type:'move'}>,state:BattleState){const mesh=this.unitMeshes.get(animation.unitId);if(!mesh){this.finishAnimation(state);return}mesh.visible=true;this.visuals.get(animation.unitId)?.play('move',220);const start=new THREE.Vector3(animation.from.x,0,animation.from.y),end=new THREE.Vector3(animation.to.x,0,animation.to.y);moveDust({scene:this.scene,tween:(duration,update,done)=>this.tween(duration,update,done)},start);this.tween(220,t=>{mesh.position.lerpVectors(start,end,t);mesh.position.y=Math.sin(t*Math.PI)*.12},()=>{moveDust({scene:this.scene,tween:(duration,update,done)=>this.tween(duration,update,done)},end);this.finishAnimation(state)})}
 private animateAttack(animation:Extract<BattleAnimation,{type:'attack'}>,state:BattleState,previous:BattleState){const attacker=this.unitMeshes.get(animation.unitId),target=this.unitMeshes.get(animation.targetId);if(!attacker||!target){this.finishAnimation(state);return}const affectedIds=animation.affectedTargetIds??[animation.targetId],affectedMeshes=affectedIds.map(id=>this.unitMeshes.get(id)).filter((mesh):mesh is THREE.Group=>Boolean(mesh)),before=previous.units.find(unit=>unit.id===animation.targetId),after=state.units.find(unit=>unit.id===animation.targetId),attackerUnit=state.units.find(unit=>unit.id===animation.unitId),style=attackerUnit?.attackStyle??((attackerUnit?.attackRange??1)>=4?'ranged-single':(attackerUnit?.attackRange??1)<=1?'heavy-single':'melee-aoe'),ranged=style==='ranged-single',defeated=Boolean(before&&after&&isActive(before)&&!isActive(after)),duration=defeated?700:320;attacker.visible=true;affectedMeshes.forEach(mesh=>{mesh.visible=true});this.visuals.get(animation.unitId)?.play(animation.visualAction??attackAction(animation.damageKind),320);for(const id of affectedIds){const hit=state.units.find(unit=>unit.id===id),was=previous.units.find(unit=>unit.id===id),dead=Boolean(was&&hit&&isActive(was)&&!isActive(hit));this.visuals.get(id)?.play(dead?deathAction(animation.damageKind):hitAction(animation.damageKind),duration)}const home=attacker.position.clone(),targetPos=target.position.clone(),direction=targetPos.clone().sub(home).normalize(),lunge=home.clone().addScaledVector(direction,.32);this.damageText(animation,targetPos);const fx={scene:this.scene,tween:(fxDuration:number,update:(t:number)=>void,done:()=>void)=>this.tween(fxDuration,update,done)};if(ranged)skillPulse(fx,home,animation.damageKind==='faith'?0xffefb0:0xffb36e);if(animation.damageKind==='faith'){faithBurst(fx,targetPos);if(animation.visualAction==='skill')skillPulse(fx,home,0xf1d58c)}else{healthSlash(fx,targetPos,direction);healthImpact(fx,targetPos,direction)}for(const mesh of affectedMeshes){if(mesh===target)continue;const pos=mesh.position.clone(),dir=pos.clone().sub(targetPos).normalize();if(animation.damageKind==='faith')faithBurst(fx,pos);else healthImpact(fx,pos,dir)}this.shakeCamera();this.tween(duration,t=>{const strike=Math.min(1,t*(duration/320)),attackT=strike<.38?strike/.38:(1-strike)/.62;if(!ranged)attacker.position.lerpVectors(home,lunge,Math.max(0,attackT));if(!defeated&&strike>.32&&strike<.7){const pulse=Math.sin((strike-.32)/.38*Math.PI);target.scale.setScalar(1-pulse*.14);target.position.x=targetPos.x+Math.sin(strike*70)*.025}else{target.scale.setScalar(1);target.position.x=targetPos.x}},()=>{attacker.position.copy(home);target.scale.setScalar(1);target.position.copy(targetPos);this.finishAnimation(state)})}
 private animateSkill(animation:Extract<BattleAnimation,{type:'skill'}>,state:BattleState){const attacker=this.unitMeshes.get(animation.unitId),target=this.unitMeshes.get(animation.targetId);if(!attacker||!target){this.finishAnimation(state);return}const targetUnit=state.units.find(unit=>unit.id===animation.targetId),home=attacker.position.clone(),targetPos=target.position.clone(),direction=targetPos.clone().sub(home).normalize(),fx={scene:this.scene,tween:(fxDuration:number,update:(t:number)=>void,done:()=>void)=>this.tween(fxDuration,update,done)};attacker.visible=true;target.visible=true;this.visuals.get(animation.unitId)?.play('skill',520);if(['reina-overload','odric-lock','cole-charge','arthur-guardbreak','hans-intercept'].includes(animation.skill)){healthSlash(fx,targetPos,direction);healthImpact(fx,targetPos,direction)}else if(['witness-cross','agnes-rite','agnes-veil'].includes(animation.skill)){faithBurst(fx,targetPos)}else{skillPulse(fx,targetPos,targetUnit?.team==='enemy'?0xf1d58c:0x8fe8d9)}if(animation.targetId!==animation.unitId)skillPulse(fx,home,targetUnit?.team==='enemy'?0x8fe8d9:0xf1d58c);this.tween(520,t=>{attacker.position.y=Math.sin(t*Math.PI)*.08;target.scale.setScalar(1+Math.sin(t*Math.PI)*.06)},()=>{attacker.position.copy(home);target.scale.setScalar(1);this.finishAnimation(state)})}
 private animateDefeats(units:Unit[],state:BattleState){this.inputLocked=true;const fx={scene:this.scene,tween:(fxDuration:number,update:(t:number)=>void,done:()=>void)=>this.tween(fxDuration,update,done)};for(const unit of units){const mesh=this.unitMeshes.get(unit.id);if(mesh){mesh.visible=true;deathBurst(fx,mesh.position.clone(),unit.team==='enemy'?0xa74343:0x5b9bd1)}this.visuals.get(unit.id)?.play(deathAction(unit.health<=0?'health':'faith'),700)}this.tween(700,()=>{},()=>this.finishAnimation(state))}
 private shakeCamera(){if(this.reduced)return;const home=this.camera.position.clone();this.tween(160,t=>{const pulse=Math.sin(t*Math.PI);this.camera.position.x=home.x+Math.sin(t*38)*.018*pulse;this.camera.position.z=home.z+Math.cos(t*31)*.014*pulse},()=>this.camera.position.copy(home))}
 private faithWave(position:THREE.Vector3){const wave=this.make(new THREE.RingGeometry(.2,.28,24),new THREE.MeshBasicMaterial({color:0xf4dfa2,transparent:true,opacity:.8,depthWrite:false}),false);wave.rotation.x=-Math.PI/2;wave.position.set(position.x,.08,position.z);this.scene.add(wave);this.tween(420,t=>{wave.scale.setScalar(1+t*3);(wave.material as THREE.MeshBasicMaterial).opacity=.8*(1-t)},()=>{this.scene.remove(wave);wave.geometry.dispose();(wave.material as THREE.Material).dispose()})}
 private tween(duration:number,update:(t:number)=>void,done:()=>void){const start=performance.now();const frame=(now:number)=>{const t=Math.min(1,(now-start)/duration),eased=1-Math.pow(1-t,3);update(eased);if(t<1&&this.running)requestAnimationFrame(frame);else done()};requestAnimationFrame(frame)}
 private finishAnimation(state:BattleState){for(const unit of state.units){const mesh=this.unitMeshes.get(unit.id);if(!mesh)continue;mesh.position.set(unit.position.x,0,unit.position.y);mesh.visible=isActive(unit);if(isActive(unit))this.visuals.get(unit.id)?.play('idle')}this.inputLocked=false;this.attackMode=undefined;this.drawTargets();this.renderer.domElement.style.cursor='default'}
 getSelectedId(){return this.selectedId}
 playUnitAction(unitId:string,action:VisualAction,durationMs=600){return this.visuals.get(unitId)?.play(action,durationMs)}
 setUnitVisualPhase(unitId:string,phase:number){this.visuals.get(unitId)?.setPhase(phase)}
 advanceUnitVisual(unitId:string,deltaSeconds:number){this.visuals.get(unitId)?.update(Math.max(0,Math.min(.25,deltaSeconds)));return this.visuals.get(unitId)?.actionSnapshot()}
 getUnitVisualAction(unitId:string){return this.visuals.get(unitId)?.actionSnapshot()}
 getStateSnapshot(){return structuredClone(this.state)}
 private damageText(animation:Extract<BattleAnimation,{type:'attack'}>,position:THREE.Vector3){const point=this.projectWorld(position.clone().setY(.9)),bounds=this.renderer.domElement.getBoundingClientRect(),label=document.createElement('div');label.className=`battle-float ${animation.damageKind}`;label.textContent=`${animation.critical?'暴击 · ':''}${animation.damageKind==='faith'?'信念':'生命'} −${animation.amount}`;label.style.left=`${point.x-bounds.left}px`;label.style.top=`${point.y-bounds.top}px`;this.host.append(label);setTimeout(()=>label.remove(),720)}
 resetCameraView(){this.cameraTarget.set(3.5,.35,3.5);this.cameraRotation=0;this.pinch=undefined;this.camera.zoom=1;this.camera.updateProjectionMatrix();this.syncCamera()}
 private panCamera(delta:THREE.Vector3){this.cameraTarget.x=THREE.MathUtils.clamp(this.cameraTarget.x+delta.x,1.65,5.35);this.cameraTarget.z=THREE.MathUtils.clamp(this.cameraTarget.z+delta.z,1.65,5.35);this.syncCamera()}
 private setCameraZoom(zoom:number){this.camera.zoom=THREE.MathUtils.clamp(zoom,.9,2.25);this.camera.updateProjectionMatrix();this.syncCamera()}
 private syncCamera(){const offset=this.cameraOffset.clone().applyAxisAngle(new THREE.Vector3(0,1,0),this.cameraRotation);this.camera.position.copy(this.cameraTarget).add(offset);this.camera.lookAt(this.cameraTarget)}
 private projectWorld(world:THREE.Vector3){const projected=world.project(this.camera),bounds=this.renderer.domElement.getBoundingClientRect();return{x:bounds.left+(projected.x*.5+.5)*bounds.width,y:bounds.top+(-projected.y*.5+.5)*bounds.height}}
 projectUnitCenter(unitId:string){const root=this.unitMeshes.get(unitId);if(!root)return;return this.projectWorld(root.localToWorld(new THREE.Vector3(0,.75,0)))}
 projectCellCenter(position:Position){return this.projectWorld(new THREE.Vector3(position.x,.03,position.y))}
 private resize=()=>{const w=this.host.clientWidth,h=this.host.clientHeight;if(w<2||h<2)return;const a=w/h,s=w<900?11.8:12.8;this.camera.left=-s*a/2;this.camera.right=s*a/2;this.camera.top=s/2;this.camera.bottom=-s/2;this.camera.updateProjectionMatrix();this.syncCamera();this.renderer.setSize(w,h)};
 private loop=()=>{if(!this.running)return;const t=this.clock.getElapsedTime(),delta=this.lastFrame?Math.min(.05,t-this.lastFrame):0;this.lastFrame=t;this.visuals.forEach(visual=>visual.update(delta));if(!this.reduced)for(const mesh of this.terrainMeshes){const amplitude=mesh.userData.floatAmplitude as number|undefined;if(amplitude!==undefined)mesh.position.y=(mesh.userData.floatBaseY as number??0)+Math.sin(t*1.6+(mesh.userData.floatPhase as number??0))*amplitude;}if(!this.reduced&&this.flame){this.flame.rotation.y=t*1.7;this.flame.scale.set(1+Math.sin(t*5)*.08,1+Math.sin(t*7)*.11,1+Math.sin(t*5)*.08)}if(!this.reduced&&this.ring?.visible){(this.ring.material as THREE.MeshBasicMaterial).opacity=.58+Math.sin(t*4)*.25;this.ring.rotation.z=t*.35}if(!this.reduced&&this.dust){this.dust.rotation.y=t*.018;this.dust.position.y=Math.sin(t*.25)*.08}if(!this.reduced)for(const marker of this.intentOverlays){const focused=marker.userData.intentUnitId===this.selectedId,pulse=(Math.sin(t*(focused?8.5:4.5))+1)/2;(marker.material as THREE.MeshBasicMaterial).opacity=(focused?.32:.2)+pulse*(focused?.58:.42);marker.scale.setScalar(1+pulse*(focused?.14:.08))}if(!this.reduced)for(const marker of this.attackRangeOverlays){const pulse=(Math.sin(t*3.8)+1)/2;(marker.material as THREE.MeshBasicMaterial).opacity=.1+pulse*.26;marker.scale.setScalar(.98+pulse*.04)}this.renderer.render(this.scene,this.camera);requestAnimationFrame(this.loop)};
 dispose(){this.running=false;this.resizeObserver?.disconnect();this.activePointers.clear();this.consumedPointerIds.clear();this.visuals.forEach(visual=>visual.dispose());this.visualLoader.dispose();this.illustrationLoader.dispose();this.environmentLoader.dispose();this.backgroundTexture?.dispose();this.backgroundTexture=undefined;removeEventListener('resize',this.resize);this.renderer.domElement.removeEventListener('pointerdown',this.onPointerDown);this.renderer.domElement.removeEventListener('pointerup',this.onPointerUp);this.renderer.domElement.removeEventListener('pointercancel',this.onPointerCancel);this.renderer.domElement.removeEventListener('pointermove',this.onPointerMove);this.scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.InstancedMesh||o instanceof THREE.Points){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose())}});this.renderer.dispose();this.host.replaceChildren()}
}
