import * as THREE from 'three';
import { GLTFLoader, type GLTF } from 'three/addons/loaders/GLTFLoader.js';
import { clone as cloneSkeleton } from 'three/addons/utils/SkeletonUtils.js';
import type { DamageKind, Unit } from '../game/battle';
import { runtimeModelLoadingAllowed } from './modelInventory';

export type CharacterVisualKey = 'unflagged'|'seraphina'|'reina'|'odric'|'cole'|'agnes'|'cultist-melee'|'shield-guard'|'scout'|'faith-acolyte'|'engineer'|'raider-rider'|'arthur'|'hans'|'asnoka';
export type BossVisualKey = 'boss-odric'|'boss-iron-bulwark'|'boss-veiled-avatar'|'boss-white-knight'|'boss-night-judge'|'boss-lake-god-a'|'boss-lake-god-b';
export type VisualKey = CharacterVisualKey | BossVisualKey;
export type VisualAction = 'idle'|'move'|'attack_health'|'attack_faith'|'hit_health'|'hit_faith'|'death_health'|'death_faith'|'skill'|`boss_phase_${number}`;
export interface CharacterIllustrationManifest { idle:string; attack:string; hit:string }
export interface CharacterVisualManifestEntry { url?:string; source?:'img2threejs'|'gltf'|'procedural'; illustrations?:CharacterIllustrationManifest; fallbacks?:readonly {url:string;visualScale:number}[]; enabled:boolean; visualScale:number; rotationY:number; actionAliases?:Partial<Record<VisualAction,readonly string[]>>; phases?:Readonly<Record<number,{visualKey?:VisualKey;action?:VisualAction}>>; phaseParts?:Readonly<Record<number,{show:readonly string[];hide:readonly string[]}>>; effectAnchors?:readonly string[] }
/** Versioned visual contract consumed by the runtime loader. */
export type CharacterVisualManifest = Readonly<Record<VisualKey,CharacterVisualManifestEntry>>;
const formalAliases:Partial<Record<VisualAction,readonly string[]>>={
 idle:['idle'],move:['move'],
 attack_health:['attack','attack_health','attack_primary'],
 attack_faith:['attack_faith','skill','attack','attack_health'],
 hit_health:['hit','hit_health'],hit_faith:['hit','hit_faith','hit_health'],
 death_health:['death','death_health'],death_faith:['death','death_faith','death_health'],
 skill:['skill','attack_faith','attack'],
};
const ironBossAliases:Partial<Record<VisualAction,readonly string[]>>={
 idle:['Idle'],move:['Walking_A','Running_A'],
 attack_health:['2H_Melee_Attack_Chop','1H_Melee_Attack_Chop'],
 attack_faith:['attack_faith','attack_health','Spellcast_Shoot','Spellcast_Raise'],
 hit_health:['Hit_A','Block_Hit'],hit_faith:['Hit_B','Hit_A'],
 death_health:['Death_A','Death_B'],death_faith:['Death_B','Death_A'],
 skill:['Cheer','Block_Attack'],
 boss_phase_1:['idle'],boss_phase_2:['phase_transition','attack_health'],
};
export const characterVisualManifest:CharacterVisualManifest={
 unflagged:{url:'/assets/models/k3/heroes/unflagged.glb',illustrations:{idle:'/assets/illustrations/battle/unflagged/idle.webp',attack:'/assets/illustrations/battle/unflagged/attack.webp',hit:'/assets/illustrations/battle/unflagged/hit.webp'},fallbacks:[{url:'/assets/models/heroes/unflagged.glb',visualScale:.7963}],enabled:true,visualScale:.7963,rotationY:0,actionAliases:formalAliases},
 seraphina:{url:'/assets/models/k3/heroes/seraphina.glb',illustrations:{idle:'/assets/illustrations/battle/seraphina/idle.webp',attack:'/assets/illustrations/battle/seraphina/attack.webp',hit:'/assets/illustrations/battle/seraphina/hit.webp'},fallbacks:[{url:'/assets/models/heroes/seraphina.glb',visualScale:.7491}],enabled:true,visualScale:.7491,rotationY:0,actionAliases:formalAliases,effectAnchors:['HeadAnchor','WeaponAnchor','HitAnchor','FootAnchor','FxLantern','FxWeapon']},
 reina:{url:'/assets/models/k3/heroes/reina.glb',illustrations:{idle:'/assets/illustrations/battle/reina/idle.webp',attack:'/assets/illustrations/battle/reina/attack.webp',hit:'/assets/illustrations/battle/reina/hit.webp'},fallbacks:[{url:'/assets/models/heroes/reina.glb',visualScale:.7657}],enabled:true,visualScale:.7657,rotationY:0,actionAliases:formalAliases},
 odric:{url:'/assets/models/heroes/odric.glb',illustrations:{idle:'/assets/illustrations/battle/odric/idle.webp',attack:'/assets/illustrations/battle/odric/attack.webp',hit:'/assets/illustrations/battle/odric/hit.webp'},enabled:true,visualScale:.7795,rotationY:0,actionAliases:formalAliases},
 cole:{url:'/assets/models/heroes/cole.glb',illustrations:{idle:'/assets/illustrations/battle/cole/idle.webp',attack:'/assets/illustrations/battle/cole/attack.webp',hit:'/assets/illustrations/battle/cole/hit.webp'},enabled:true,visualScale:.7873,rotationY:0,actionAliases:formalAliases},
 agnes:{url:'/assets/models/heroes/agnes.glb',illustrations:{idle:'/assets/illustrations/battle/agnes/idle.webp',attack:'/assets/illustrations/battle/agnes/attack.webp',hit:'/assets/illustrations/battle/agnes/hit.webp'},enabled:true,visualScale:.7791,rotationY:0,actionAliases:formalAliases},
 'cultist-melee':{url:'/assets/models/enemies/cultist-melee.glb',enabled:true,visualScale:.7777,rotationY:0},
 'shield-guard':{url:'/assets/models/enemies/mainline/shield-guard.glb',source:'img2threejs',enabled:true,visualScale:.76,rotationY:0,actionAliases:formalAliases,effectAnchors:['HeadAnchor','WeaponAnchor','HitAnchor','FootAnchor']},
 scout:{url:'/assets/models/enemies/mainline/scout.glb',source:'img2threejs',enabled:true,visualScale:.76,rotationY:0,actionAliases:formalAliases,effectAnchors:['HeadAnchor','WeaponAnchor','HitAnchor','FootAnchor']},
 'faith-acolyte':{url:'/assets/models/enemies/mainline/faith-acolyte.glb',source:'img2threejs',enabled:true,visualScale:.76,rotationY:0,actionAliases:{...formalAliases,attack_health:['attack_faith','attack_health'],hit_faith:['hit_health'],death_faith:['death_health']},effectAnchors:['HeadAnchor','WeaponAnchor','HitAnchor','FootAnchor']},
 engineer:{url:'/assets/models/enemies/mainline/engineer.glb',source:'img2threejs',enabled:true,visualScale:.76,rotationY:0,actionAliases:formalAliases,effectAnchors:['HeadAnchor','WeaponAnchor','HitAnchor','FootAnchor']},
 'raider-rider':{url:'/assets/models/enemies/mainline/raider-rider.glb',source:'img2threejs',enabled:true,visualScale:.78,rotationY:0,actionAliases:formalAliases,effectAnchors:['HeadAnchor','WeaponAnchor','HitAnchor','FootAnchor']},
 // Mainline img2threejs slots. Until the formal GLBs arrive these entries stay
 // disabled so release builds never request a missing asset and use unitModel().
 arthur:{url:'/assets/models/mainline/arthur.glb',source:'img2threejs',illustrations:{idle:'/assets/illustrations/mainline/arthur/idle-gpt-image-2.webp',attack:'/assets/illustrations/mainline/arthur/attack-gpt-image-2.webp',hit:'/assets/illustrations/mainline/arthur/hit-gpt-image-2.webp'},enabled:true,visualScale:.76,rotationY:0,actionAliases:formalAliases,effectAnchors:['HeadAnchor','WeaponAnchor','HitAnchor','FootAnchor','FxWeapon']},
 hans:{url:'/assets/models/mainline/hans.glb',source:'img2threejs',illustrations:{idle:'/assets/illustrations/battle/hans/idle.webp',attack:'/assets/illustrations/battle/hans/attack.webp',hit:'/assets/illustrations/battle/hans/hit.webp'},enabled:true,visualScale:.74,rotationY:0,actionAliases:formalAliases,effectAnchors:['HeadAnchor','WeaponAnchor','HitAnchor','FootAnchor','FxWeapon']},
 asnoka:{url:'/assets/models/mainline/asnoka.glb',source:'img2threejs',illustrations:{idle:'/assets/illustrations/battle/asnoka/idle.webp',attack:'/assets/illustrations/battle/asnoka/attack.webp',hit:'/assets/illustrations/battle/asnoka/hit.webp'},enabled:true,visualScale:.76,rotationY:0,actionAliases:formalAliases,effectAnchors:['HeadAnchor','WeaponAnchor','HitAnchor','FootAnchor','FxWeapon']},
 'boss-odric':{url:'/assets/models/bosses/odric-judgment.glb',fallbacks:[{url:'/assets/models/heroes/odric.glb',visualScale:.7795}],enabled:true,visualScale:1.5,rotationY:0,actionAliases:{...formalAliases,boss_phase_1:['idle'],boss_phase_2:['phase_transition','attack_health']},phaseParts:{1:{show:['Phase1Parts'],hide:['Phase2Parts']},2:{show:['Phase2Parts'],hide:['Phase1Parts']}}},
 'boss-iron-bulwark':{url:'/assets/models/bosses/iron-bulwark.glb',fallbacks:[{url:'/assets/models/enemies/cultist-melee.glb',visualScale:.92}],enabled:true,visualScale:1.6,rotationY:0,actionAliases:ironBossAliases,phaseParts:{1:{show:['Phase1Parts'],hide:['Phase2Parts']},2:{show:['Phase2Parts'],hide:['Phase1Parts']}}},
 'boss-veiled-avatar':{url:'/assets/models/bosses/veiled-avatar.glb',fallbacks:[{url:'/assets/models/heroes/seraphina.glb',visualScale:.7491}],enabled:true,visualScale:1,rotationY:0,actionAliases:{...formalAliases,attack_health:['attack_faith'],boss_phase_1:['idle'],boss_phase_2:['phase_transition']},phaseParts:{1:{show:['Phase1Parts'],hide:['Phase2Parts']},2:{show:['Phase2Parts'],hide:['Phase1Parts']}}},
 'boss-white-knight':{url:'/assets/models/mainline/boss-white-knight.glb',source:'img2threejs',illustrations:{idle:'/assets/illustrations/battle/boss-white-knight/idle.webp',attack:'/assets/illustrations/battle/boss-white-knight/attack.webp',hit:'/assets/illustrations/battle/boss-white-knight/hit.webp'},enabled:true,visualScale:.85,rotationY:0,actionAliases:{...formalAliases,boss_phase_1:['idle'],boss_phase_2:['phase_transition','attack_health']},phaseParts:{1:{show:['Phase1Parts'],hide:['Phase2Parts']},2:{show:['Phase2Parts'],hide:['Phase1Parts']}},effectAnchors:['HeadAnchor','WeaponAnchor','HitAnchor','FootAnchor','FxWeapon']},
 'boss-night-judge':{url:'/assets/models/mainline/boss-night-judge.glb',source:'img2threejs',illustrations:{idle:'/assets/illustrations/battle/boss-night-judge/idle.webp',attack:'/assets/illustrations/battle/boss-night-judge/attack.webp',hit:'/assets/illustrations/battle/boss-night-judge/hit.webp'},enabled:true,visualScale:.78,rotationY:0,actionAliases:{...formalAliases,boss_phase_1:['idle'],boss_phase_2:['phase_transition','attack_faith']},phaseParts:{1:{show:['Phase1Parts'],hide:['Phase2Parts']},2:{show:['Phase2Parts'],hide:['Phase1Parts']}},effectAnchors:['HeadAnchor','WeaponAnchor','HitAnchor','FootAnchor','FxWeapon']},
 'boss-lake-god-a':{url:'/assets/models/mainline/boss-lake-god-a.glb',source:'img2threejs',illustrations:{idle:'/assets/illustrations/battle/boss-lake-god-a/idle.webp',attack:'/assets/illustrations/battle/boss-lake-god-a/attack.webp',hit:'/assets/illustrations/battle/boss-lake-god-a/hit.webp'},enabled:true,visualScale:.92,rotationY:0,actionAliases:{...formalAliases,boss_phase_1:['idle'],boss_phase_2:['phase_transition','attack_faith']},phaseParts:{1:{show:['Phase1Parts'],hide:['Phase2Parts']},2:{show:['Phase2Parts'],hide:['Phase1Parts']}},effectAnchors:['CoreAnchor','HitAnchor','FxCore']},
 'boss-lake-god-b':{url:'/assets/models/mainline/boss-lake-god-b.glb',source:'img2threejs',illustrations:{idle:'/assets/illustrations/battle/boss-lake-god-b/idle.webp',attack:'/assets/illustrations/battle/boss-lake-god-b/attack.webp',hit:'/assets/illustrations/battle/boss-lake-god-b/hit.webp'},enabled:true,visualScale:.92,rotationY:0,actionAliases:{...formalAliases,boss_phase_1:['idle'],boss_phase_2:['phase_transition','attack_faith']},phaseParts:{1:{show:['Phase1Parts'],hide:['Phase2Parts']},2:{show:['Phase2Parts'],hide:['Phase1Parts']}},effectAnchors:['CoreAnchor','HitAnchor','FxCore']},
};
const aliases:Readonly<Record<Exclude<VisualAction,`boss_phase_${number}`>,readonly string[]>>={idle:['idle'],move:['move','idle'],attack_health:['attack_health','attack','attack_primary','skill','move','idle'],attack_faith:['attack_faith','skill','attack','attack_health','attack_primary','move','idle'],hit_health:['hit_health','hit','death_health','death','idle'],hit_faith:['hit_faith','hit_health','hit','death_faith','death_health','death','idle'],death_health:['death_health','death','hit_health','hit','idle'],death_faith:['death_faith','death_health','death','hit_faith','hit_health','hit','idle'],skill:['skill','attack_faith','attack_health','attack','move','idle']};
const unitVisualKeys:Readonly<Record<string,VisualKey>>={u1:'unflagged',u2:'seraphina',u3:'reina',u4:'odric',u5:'cole',u6:'agnes','u-arthur':'arthur','u-hans':'hans','u-asnoka':'asnoka',e3:'cultist-melee','boss-odric':'boss-odric','boss-iron-bulwark':'boss-iron-bulwark','boss-veiled-avatar':'boss-veiled-avatar','boss-white-knight':'boss-white-knight','boss-night-judge':'boss-night-judge','boss-lake-god-a':'boss-lake-god-a','boss-lake-god-b':'boss-lake-god-b'};
export function visualKeyForUnit(unit:Pick<Unit,'id'|'visualKey'>):VisualKey|undefined {
 const explicit=unit.visualKey as VisualKey|undefined;
 return explicit&&explicit in characterVisualManifest?explicit:unitVisualKeys[unit.id];
}
export interface VisualActionPlayback {requestedAction:VisualAction;clip:string;fallbackUsed:boolean;duration:number;time:number;timeScale:number;running:boolean;weight:number}
export interface CharacterVisualInstance {root:THREE.Group;hitTarget:THREE.Mesh;play(action:VisualAction,durationMs?:number):VisualActionPlayback|undefined;setPhase(phase:number):void;update(delta:number):void;actionSnapshot():VisualActionPlayback|undefined;anchor(name:string):THREE.Object3D|undefined;usingFallback():boolean;dispose():void}
export class CharacterVisualLoader{
 private loader=new GLTFLoader();private cache=new Map<string,Promise<GLTF>>();private loaded=new Set<GLTF>();private disposed=false;
 constructor(private loadAsset?:((url:string)=>Promise<GLTF>)){}
 create(unit:Unit,fallback:THREE.Group):CharacterVisualInstance{
  const root=new THREE.Group();root.name=`visual-${unit.id}`;root.add(fallback);const hitProxy=new THREE.Mesh(new THREE.BoxGeometry(.72,1.5,.72),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));hitProxy.name=`${unit.id}-hit-proxy`;hitProxy.position.y=.75;hitProxy.userData.unitId=unit.id;root.add(hitProxy);const key=visualKeyForUnit(unit),entry=key?characterVisualManifest[key]:undefined;let mixer:THREE.AnimationMixer|undefined,clips:THREE.AnimationClip[]=[],model:THREE.Object3D|undefined,current:THREE.AnimationAction|undefined,currentRequest:VisualAction|undefined,pending:{action:VisualAction;durationMs?:number}|undefined,fallbackActive=true,localDisposed=false;
  const snapshot=():VisualActionPlayback|undefined=>current&&currentRequest?{requestedAction:currentRequest,clip:current.getClip().name,fallbackUsed:current.getClip().name.toLowerCase()!==currentRequest.toLowerCase(),duration:current.getClip().duration,time:current.time,timeScale:current.timeScale,running:current.isRunning(),weight:current.getEffectiveWeight()}:undefined;
  const candidates=(action:VisualAction)=>{const base=action.startsWith('boss_phase_')?[action,'skill','attack_faith','attack_health','attack','idle']:(aliases[action as Exclude<VisualAction,`boss_phase_${number}`>]??[action,'idle']);return[...(entry?.actionAliases?.[action]??[]),...base].filter((name,index,all)=>all.findIndex(other=>other.toLowerCase()===name.toLowerCase())===index)};
  const play=(action:VisualAction,durationMs?:number)=>{if(!mixer){pending={action,durationMs};return}const names=candidates(action),clip=names.map(name=>clips.find(item=>item.name.toLowerCase()===name.toLowerCase())).find(Boolean)??clips[0];if(!clip)return;const next=mixer.clipAction(clip);next.reset().setLoop(action==='idle'||action==='move'?THREE.LoopRepeat:THREE.LoopOnce,action==='idle'||action==='move'?Infinity:1);next.clampWhenFinished=action.startsWith('death_');next.timeScale=durationMs&&clip.duration>0?clip.duration/(durationMs/1000):1;if(current&&current!==next)current.fadeOut(.08);next.fadeIn(.08).play();current=next;currentRequest=action;const result=snapshot()!;dispatchEvent(new CustomEvent('goddess-character-action',{detail:{unitId:unit.id,key,action,clip:clip.name,fallbackUsed:result.fallbackUsed,timeScale:result.timeScale}}));return result};
  const setPhase=(phase:number)=>{const parts=entry?.phaseParts?.[phase];if(!model||!parts)return;const show=new Set(parts.show),hide=new Set(parts.hide);model.traverse(child=>{if(show.has(child.name))child.visible=true;if(hide.has(child.name))child.visible=false});root.userData.visualPhase=phase};
  if((this.loadAsset||runtimeModelLoadingAllowed(entry?.url??''))&&entry?.enabled&&entry.url)this.loadFirst([{url:entry.url,visualScale:entry.visualScale},...(entry.fallbacks??[])]).then(({gltf,url,visualScale})=>{if(this.disposed||localDisposed)return;model=cloneSkeleton(gltf.scene);model.name=`${key}-model`;model.userData.visualSourceUrl=url;root.userData.visualSourceUrl=url;model.scale.setScalar(visualScale);model.rotation.y=entry.rotationY;let meshCount=0;model.traverse(child=>{child.userData.visualUnitId=unit.id;if(child instanceof THREE.Mesh){meshCount++;child.geometry=child.geometry.clone();child.material=Array.isArray(child.material)?child.material.map(material=>material.clone()):child.material.clone();child.castShadow=true;child.receiveShadow=true}});root.remove(fallback);this.disposeObject(fallback);root.add(model);setPhase(1);root.updateWorldMatrix(true,true);const bounds=new THREE.Box3().setFromObject(model),origin=root.getWorldPosition(new THREE.Vector3());fallbackActive=false;clips=gltf.animations;mixer=new THREE.AnimationMixer(model);dispatchEvent(new CustomEvent('goddess-character-ready',{detail:{unitId:unit.id,key,url,meshCount,raycastTagged:true,clips:clips.map(clip=>clip.name),bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()},origin:origin.toArray(),collisionRadius:.36}}));const queued=pending;pending=undefined;play(queued?.action??'idle',queued?.durationMs)}).catch(()=>{root.userData.visualSourceUrl='procedural';dispatchEvent(new CustomEvent('goddess-character-ready',{detail:{unitId:unit.id,key,url:'procedural',meshCount:0,raycastTagged:true,clips:[]}}))});
  return{root,hitTarget:hitProxy,play,setPhase,update:delta=>mixer?.update(delta),actionSnapshot:snapshot,anchor:name=>model?.getObjectByName(name),usingFallback:()=>fallbackActive,dispose:()=>{localDisposed=true;pending=undefined;mixer?.stopAllAction();if(model){mixer?.uncacheRoot(model);this.disposeObject(model)}dispatchEvent(new CustomEvent('goddess-character-disposed',{detail:{unitId:unit.id,key,url:root.userData.visualSourceUrl??'procedural'}}))}};
 }
 private async loadFirst(candidates:readonly {url:string;visualScale:number}[]){let lastError:unknown;for(const candidate of candidates){try{return{gltf:await this.load(candidate.url),...candidate}}catch(error){lastError=error}}throw lastError}
 private load(url:string){const cached=this.cache.get(url);if(cached)return cached;const pending=(this.loadAsset?.(url)??this.loader.loadAsync(url)).then(gltf=>{if(this.disposed)this.disposeObject(gltf.scene);else this.loaded.add(gltf);return gltf}).catch(error=>{this.cache.delete(url);throw error});this.cache.set(url,pending);return pending}
 private disposeObject(root:THREE.Object3D){root.traverse(child=>{if(!(child instanceof THREE.Mesh))return;child.geometry.dispose();for(const material of Array.isArray(child.material)?child.material:[child.material])material.dispose()})}
 dispose(){this.disposed=true;for(const gltf of this.loaded)this.disposeObject(gltf.scene);this.loaded.clear();this.cache.clear()}
}
export const attackAction=(kind:DamageKind):VisualAction=>kind==='faith'?'attack_faith':'attack_health';
export const hitAction=(kind:DamageKind):VisualAction=>kind==='faith'?'hit_faith':'hit_health';
export const deathAction=(kind:DamageKind):VisualAction=>kind==='faith'?'death_faith':'death_health';
