import type { MilestoneAWeekContent } from "./campaignWeekOne";

export const campaignWeekTwo: MilestoneAWeekContent = {
  id: "act1_week2_iron_road",
  actLabel: "第二幕 · 铁窗与粮路",
  weekLabel: "第二周 · 雨中的粮车",
  homeHeadline: "封路机守住了边境，也让两座村庄断粮。",
  route: [
    {
      id: "iron_bulwark",
      sequence: 1,
      title: "会移动的城墙",
      kind: "battle",
      location: "新卡瓦拉 · 北灌渠",
      objective: "击破指挥装甲，迫使移动壁垒停止封锁粮路。",
      risk: "高",
      knownThreat: "装甲破裂后壁垒会解除限速，攻击与意图同步改变。",
      consequence: "公开证据或换取停火，将改变卫道士与河湾的态度。",
      status: "next",
    },
    {
      id: "grain_contracts",
      sequence: 2,
      title: "重复签发的粮契",
      kind: "investigation",
      location: "新卡瓦拉 · 河湾仓区",
      objective: "核对粮运契约与壁垒采购编号。",
      risk: "中",
      knownThreat: "利益链可能在使团抵达前焚毁账目。",
      consequence: "完整证据将影响后续停火条件。",
      status: "future",
    },
    {
      id: "silent_columns",
      sequence: 3,
      title: "无声行军",
      kind: "battle",
      location: "黑色教庭边界 · 雾门",
      objective: "护送档案通过三处雾门。",
      risk: "高",
      knownThreat: "部分敌方意图会被雾遮蔽。",
      consequence: "档案是否抵达决定终章可用的非歼灭解法。",
      status: "future",
    },
  ],
  actions: [
    {
      id: "investigate",
      title: "核对动力编号",
      description: "蕾娜比对封路机与工坊记录。",
      immediateEffect: "情报提升；Boss 第二阶段弱点提前公开。",
      battleEffect: "战前简报确认阶段转换与动力核心位置。",
    },
    {
      id: "rest",
      title: "照料断粮村民",
      description: "塞拉菲娜组织临时灶台并处理队伍伤势。",
      immediateEffect: "清除一名成员的疲劳，队伍凝聚 +1。",
      battleEffect: "成员状态写入战前准备，不改变基础伤害。",
    },
    {
      id: "negotiate",
      title: "向赫尔曼发出停机要求",
      description: "以圣火案件证物要求卫道士议会公开答复。",
      immediateEffect: "保留证物并建立谈判记录。",
      battleEffect: "敌方意图仍公开；战后增加停火选项的叙事依据。",
    },
  ],
  roster: [
    {
      characterId: "the_unflagged",
      roleName: "使节 / 见证人",
      condition: "正常",
      readiness: "可在战后决定证据公开方式。",
      relationshipNote: "必须在粮路与完整证据之间承担取舍。",
      selected: true,
    },
    {
      characterId: "seraphina",
      roleName: "调停者",
      condition: "疲劳",
      readiness: "信念攻击可使装甲指挥者退场。",
      relationshipNote: "她要求任何停火都必须先让粮车通过。",
      selected: true,
    },
    {
      characterId: "reina",
      roleName: "工程师",
      condition: "正常",
      readiness: "掌握壁垒动力结构与阶段转换情报。",
      relationshipNote: "她必须决定是否公开自己国家的军工记录。",
      selected: true,
    },
  ],
  battlePreparation: {
    title: "战前准备 · 会移动的城墙",
    objective: "击破指挥装甲，随后截停解除限速的动力核心。",
    terrain: "8×8 灌渠；壁垒位于北侧，两名护卫封锁侧翼。",
    knownIntent: "Boss 进入第二阶段后攻击增强；阶段名称与下一步意图会持续显示。",
    evidencePrompt: "动力编号决定你是否提前知道第二阶段弱点。",
    launchLabel: "开战",
  },
  postBattle: {
    victory: {
      result: "victory",
      headline: "壁垒停机，粮车终于穿过北灌渠。",
      summary: "指挥装甲与动力核心先后失效，重复采购记录也从壁垒中被发现。",
      changes: ["粮路恢复", "获得壁垒采购记录", "卫道士态度将根据证据处理方式变化"],
      nextWeekNotice: "下一行动将核对粮契，并追查让边境冲突持续获利的人。",
      recommendedNextAction: "investigate",
    },
    defeat: {
      result: "defeat",
      headline: "壁垒越过灌渠，粮路仍在封锁。",
      summary: "使团撤回河湾，但已经确认动力核心会在第二阶段暴露。",
      changes: ["口粮 -1", "下一行动风险：警戒升级", "保留阶段情报"],
      nextWeekNotice: "故事继续；先调查可在下一次行动中保留动力节点情报。",
      recommendedNextAction: "investigate",
    },
  },
};
