import type { MilestoneAWeekContent } from "./campaignWeekOne";

export const campaignWeekThree: MilestoneAWeekContent = {
  id: "act1_week3_veiled_dawn",
  actLabel: "第三幕 · 帷幕后之光",
  weekLabel: "第三周 · 无名黎明",
  homeHeadline: "三条证据指向同一座封闭圣所，却没有一条能够证明女神是否存在。",
  route: [
    {
      id: "veiled-sanctum",
      sequence: 1,
      title: "帷幕圣所",
      kind: "battle",
      location: "圣辉城外环 · 无名穹顶",
      objective: "让灯油、余烬与异制工具在公开见证下接受同一次检验。",
      risk: "高",
      knownThreat: "守幕圣像会在外壳破裂后改变形态与意图。",
      consequence: "摧毁容器、动摇共同信念或提交完整证据，将导向不同结局。",
      status: "next",
    },
    {
      id: "public-testimony",
      sequence: 2,
      title: "三份见证",
      kind: "investigation",
      location: "圣辉城 · 公议阶",
      objective: "决定证据由谁保管、以何种顺序公开。",
      risk: "高",
      knownThreat: "任何单一阵营都可能把不确定性改写成自己的答案。",
      consequence: "真相可以被保留，但无法替所有人证明神迹。",
      status: "future",
    },
    {
      id: "unflagged-dawn",
      sequence: 3,
      title: "无旗黎明",
      kind: "investigation",
      location: "三国边界 · 旧钟塔",
      objective: "记录第一季结局与仍未回答的问题。",
      risk: "中",
      knownThreat: "确定的证据与无法确定的女神将同时留下。",
      consequence: "下一季从各方如何利用这份空白开始。",
      status: "future",
    },
  ],
  actions: [
    {
      id: "investigate",
      title: "校对三条证据链",
      description: "把守灯账簿、无温余烬与异制工具置于同一时间线。",
      immediateEffect: "情报提升；完整证据路线会在圣所前公开。",
      battleEffect: "提前显示守幕圣像的阶段转换条件。",
    },
    {
      id: "rest",
      title: "安置最后一批见证人",
      description: "让受伤者先离开穹顶周边。",
      immediateEffect: "清除一名成员的疲劳，队伍凝聚 +1。",
      battleEffect: "不改变基础伤害，保留完整撤离路线。",
    },
    {
      id: "negotiate",
      title: "要求三方共同旁听",
      description: "拒绝让任何一方独占检验过程。",
      immediateEffect: "建立公开记录，并保留现有证物。",
      battleEffect: "敌方意图继续公开，结局保留多方见证。",
    },
  ],
  roster: [
    { characterId: "the_unflagged", roleName: "无旗见证人", condition: "正常", readiness: "负责提交证据并拒绝替证据补写神谕。", relationshipNote: "必须接受真相可能仍不完整。", selected: true },
    { characterId: "seraphina", roleName: "信念调停者", condition: "疲劳", readiness: "可以从信念侧击溃圣像，但不会宣称女神因此消失。", relationshipNote: "她要区分信仰、制度与神的真实性。", selected: true },
    { characterId: "reina", roleName: "装置检验官", condition: "正常", readiness: "可以从生命侧拆毁容器并保存机械记录。", relationshipNote: "她承认能解释装置，不等于能解释所有体验。", selected: true },
  ],
  battlePreparation: {
    title: "战前准备 · 帷幕圣所",
    objective: "面对 Tier 3 守幕圣像；外壳破裂后进入第二阶段。",
    terrain: "8×8 无名穹顶；四角见证灯会标记敌方下一步意图。",
    knownIntent: "第二阶段同时增强移动与两类攻击；生命、信念与完整证据均可解决冲突。",
    evidencePrompt: "三件证物齐全时，可在开战前选择公开检验。",
    launchLabel: "进入圣所",
  },
  postBattle: {
    victory: {
      result: "victory",
      headline: "帷幕落下，但光的来源仍没有唯一答案。",
      summary: "容器、信念或证据结束了冲突；没有人能够据此证明女神存在或不存在。",
      changes: ["三条证据链完成归档", "圣所停止裁决", "各方保留不同解释"],
      nextWeekNotice: "第一季结局已记录；无旗使团将带着未决问题离开圣辉城。",
      recommendedNextAction: "investigate",
    },
    defeat: {
      result: "defeat",
      headline: "使团撤出圣所，见证仍然穿过了帷幕。",
      summary: "守幕圣像没有被击溃，但公开记录让圣所无法再独占解释。",
      changes: ["保留三条证据链", "队伍撤离", "女神真实性仍未定论"],
      nextWeekNotice: "第一季以未完成的检验收束；失败不会删除已经公开的证据。",
      recommendedNextAction: "investigate",
    },
  },
};
