import type {DialogueNode} from "./types";

export const holyFlameExpansionNodes:Record<string,DialogueNode>={
  "seraphina-vault":{
    id:"seraphina-vault",kind:"dialogue",title:"地下档案馆的第十三把钥匙",focusCharacterId:"seraphina",
    lines:[
      {text:"塞拉菲娜没有把你带去守灯人的值房，而是绕过正在集结的银甲骑士，推开圣光殿侧廊一扇没有徽记的小门。门后向下的石阶很窄，墙上每隔七步才有一盏副灯。她提着灯走在最前面，熟悉每一道转角，却在最后一扇门前停了很久。"},
      {speakerId:"seraphina",emotion:"doubt",text:"我六岁那年被带进这座城。祭司告诉我，门外的世界会用怀疑污染神谕；后来他们又告诉我，只有我能替门外的人理解神谕。我直到十七岁才发现，这两句话不能同时是真的。"},
      {speakerId:"the_unflagged",text:"所以你开始找原始记录。不是解释过的抄本，不是枢机团批准过的节录，而是第一次写下那些话的人究竟看见了什么。"},
      {speakerId:"seraphina",emotion:"resolve",text:"地下第七库保存祭坛维修簿，第八库保存历任圣女的梦记，第十三库没有目录。盲眼的艾利阿斯说，目录被删掉不等于东西不存在。他把钥匙缝进我的礼袍，却不肯告诉我门里有什么。"},
      {text:"门内没有神迹遗物，只有成排受潮的木匣。最旧的一匣记录圣火在三次暴雨后由工匠重建，纸边写着“不得让朝圣者看见停火”。另一匣记载圣女在高烧中说过一句含混的话，公开神谕却多出了整整三页命令。"},
      {speakerId:"seraphina",emotion:"fear",text:"这些不能证明女神没有来过。也不能证明她来过。它们只能证明，有人总在她沉默的时候替她补上句子。我每天站在祭坛前诵读那些句子，却不知道哪一行属于谁。"},
      {speakerId:"the_unflagged",text:"你现在可以把匣子交给骑士，保住你在城里的位置；也可以带走一页原始维修记录，让守灯人的账不再只是一个老妇人的口供。无论选哪一个，都不是女神替你选。"},
      {text:"远处传来第十四声钟响。塞拉菲娜把手按在无目录的木匣上，没有祈祷。她第一次用自己的名字，而不是圣女的职衔，在借阅页上写下“塞拉菲娜取阅，愿承担后果”。"},
    ],
    choices:[
      {id:"seraphina-copy-record",label:"带走原始维修页",hint:"塞拉菲娜承担私取档案的责任；圣辉守军的信念防线会因记录动摇。",effects:{setFlags:["heard_seraphina_archive"],statChanges:{goddessTrust:-1,publicFaith:-3}},next:"keeper"},
      {id:"seraphina-seal-vault",label:"封好木匣，只记下目录位置",hint:"暂不夺走原件，保留日后公开核验的可能。",effects:{setFlags:["seraphina_preserved_archive"],statChanges:{goddessTrust:1}},next:"keeper"},
    ],
  },
  "reina-altar-memory":{
    id:"reina-altar-memory",kind:"dialogue",title:"石阶下面的工程图",focusCharacterId:"reina",
    lines:[
      {text:"蕾娜趁骑士换岗钻进祭坛下方。外面的人把这里称作圣火的根，里面却像一间被匆忙封死的工坊：铜管从墙后汇入油槽，齿轮带动一组打磨过的晶片，地面留着反复拆装的划痕。她没有立刻嘲笑，只蹲下来逐一摸过螺帽。"},
      {speakerId:"reina",emotion:"doubt",text:"这种锁扣是铁砧堡工程学校二十年前的旧制。我的第一份毕业作业就是改良它。那时老师说，结构没有立场，谁都可以用。现在它藏在祭坛下面，替某种立场发光。"},
      {speakerId:"the_unflagged",text:"你认得制造方法，不等于你制造了这座祭坛。可一旦公开，女神国会说卫道士伪造神迹，卫道士会说这证明所有信仰都该被拆除。两边都只会拿走对自己有用的一半。"},
      {speakerId:"reina",emotion:"anger",text:"铁砧堡最喜欢说“只谈可测量之物”。可他们从不测量一台机器让谁获利，也不测量命令落下时谁被压在履带下面。我曾以为把世界画成图纸，就能让每个人看见同一件事。"},
      {text:"她从油槽背面刮下一层黑色密封蜡。蜡里混有圣辉城常用的香料，也有铁砧堡为防矿尘加入的石粉。两种材料并不能指认唯一凶手，只能说明有人长期让敌对双方共享同一条隐秘供应线。"},
      {speakerId:"reina",emotion:"resolve",text:"我可以当场拆掉幻光轴，让广场的人亲眼看见火如何被制造；也可以只标记接口，等我们拿到采购记录再动手。前者救蕾娜这个嫌疑人，后者也许能救更多以后被嫁祸的人。"},
      {speakerId:"seraphina",emotion:"doubt",text:"如果你拆，祭坛会彻底熄灭；如果你不拆，骑士可能在我们找到记录以前重新点亮它。我无法告诉你哪一种更接近诚实，因为我自己也刚知道脚下有这间房。"},
      {text:"蕾娜把工具递给你。那不是请你替工程师判断结构，而是请你决定证据应当先成为公开的震动，还是一条仍能追向幕后买家的细线。"},
    ],
    choices:[
      {id:"mark-hidden-joints",label:"标记接口并保留完整装置",hint:"保全证据链，蕾娜可在战斗前指出机关盲区。",effects:{setFlags:["reina_mapped_altar"],statChanges:{wardenTrust:1}},next:"altar"},
      {id:"disable-light-axle",label:"拆下幻光轴，阻止再次伪造火焰",hint:"立即终止装置运转，但圣辉城对使团更敌视。",effects:{setFlags:["reina_disabled_altar"],statChanges:{publicFaith:-6,goddessTrust:-2,wardenTrust:1}},next:"altar"},
    ],
  },
  "unflagged-night-letter":{
    id:"unflagged-night-letter",kind:"dialogue",title:"没有旗的来信",focusCharacterId:"the_unflagged",
    lines:[
      {text:"调查暂时告一段落时，一只灰脚海鸟落在回廊窗沿。它脚上的铜环不是大陆任何城邦的印记，而是一月王国海鸟斥候使用的潮汐刻度。纸条只有半页，墨水带着海盐，开头没有称谓。"},
      {speakerId:"the_unflagged",emotion:"doubt",text:"他们问我，圣辉城是否已经准备好让流亡者回来；还问我，如果城里仍把所有反对者称为异端，我会不会替一月王国举旗。这个问题从我踏上海岸那天起就没有离开。"},
      {speakerId:"seraphina",text:"你来自他们，却不穿他们的颜色。城里因此允许你走进祭坛，铁砧堡也因此没有立刻把你当敌军。无旗给了你通行权，可这份通行权是不是也要求你永远不要承认自己属于谁？"},
      {speakerId:"the_unflagged",emotion:"resolve",text:"一月王国不是抽象的立场。那里有在船上出生、从没踩过大陆泥土的孩子，也有记得女神军从天空而来的老人。他们曾经让一支自称神使的军队撤退，但那不能证明他们击伤了神，只能证明军队会流血。"},
      {speakerId:"reina",text:"如果你公开来自一月王国，奥德里克会把今天当成海外势力策动的颠覆；如果你继续沉默，流亡者会说你拿他们的经历换取大陆人的信任。工程图上没有这种两边都正确的裂缝。"},
      {text:"纸条背面列着三个名字：在第一次登陆中失踪的斥候、被圣辉骑士收养的流亡孤儿、仍被关在地下档案馆的老水手。没有一个名字要求你证明女神真假，他们只要求你别让自己的中立成为又一道删去姓名的程序。"},
      {speakerId:"the_unflagged",emotion:"resolve",text:"我不会在圣辉城升起一月的旗，也不会否认这封信来自哪里。证物交给公开见证，名字写进记录。我失去某一边的通行权，也比让所有人继续猜测我在替谁说话好。"},
      {text:"你在回信上写下：使团不代表王国宣战，也不替女神国赦免过去；若流亡者返岸，必须以见证人而不是征服者的身份来。海鸟起飞时，城门上的旗仍在风里，而你手里只剩一枚没有图案的铜环。"},
    ],
    choices:[
      {id:"declare-january-origin",label:"向同伴公开一月王国来信",hint:"无旗者拒绝用沉默换通行；之后的证据交涉更公开。",effects:{setFlags:["unflagged_declared_origin"],statChanges:{publicFaith:-2,wardenTrust:1}},next:"confrontation"},
      {id:"record-names-first",label:"先将三个名字写入证据卷",hint:"不宣布政治归属，但保证失踪者不会再次被删去。",effects:{setFlags:["unflagged_recorded_names"],statChanges:{civilianSafety:4}},next:"confrontation"},
    ],
  },
  "ash-witness-circle":{
    id:"ash-witness-circle",kind:"dialogue",title:"灰烬需要三个人作证",evidenceRecovery:true,
    lines:[
      {text:"广场战斗结束后，蕾娜没有立刻把无温余烬装箱。她在祭坛边摆出三张矮凳，请守灯人、受伤的朝圣者和一名放下武器的年轻骑士分别坐下。无旗者要求他们互不提示，依次描述钟响前后看到的火。"},
      {speakerId:"old_mara",emotion:"fear",text:"第十二声钟以前，火焰很高，却没有热浪。我以为是女神在收敛温度。灰眼人冲出来后，油才真正烧起来。我守了四十年灯，竟然直到今天才承认自己也闻得到油味。"},
      {speakerId:"seraphina",emotion:"doubt",text:"承认闻到油味，不等于否认你四十年的照料。有人借用了你的忠诚，也有人确实在那些夜里因为这盏灯找到路。我们要分开的，是火、制度和你自己的善意。"},
      {speakerId:"reina",text:"余烬里有两层沉积。下层来自普通灯油，上层是冷却后撒进去的矿灰。矿灰让表面看起来像燃烧一夜的残留。谁做了伪装仍未知，但“神迹突然熄灭”这句话已经站不住。"},
      {speakerId:"the_unflagged",text:"一件证物必须经得住敌对的人重复描述。守灯人证明维护流程，朝圣者证明体感差异，骑士证明封锁时间。三份证词互相不喜欢，却在同一个时间点重合，这比任何一方的宣言都可靠。"},
      {text:"年轻骑士承认，封锁命令在钟响前半个时辰就已盖印。命令没有写谁预见圣火会熄灭，只写“防止铁砧使者破坏祭坛”。蕾娜的名字显然早于事件被填进了答案。"},
      {speakerId:"seraphina",emotion:"anger",text:"神谕如果真的提前到来，也不该只告诉骑士准备一个替罪者。可若这只是人的命令，写下它的人比任何神秘力量都更接近我们的敌人。"},
      {text:"三人分别在证物封条上按下不同颜色的蜡印。无温余烬不再只是使团从祭坛偷走的一把灰，而成为可以被圣辉城内部的人重新检验、也可以被铁砧堡质疑的公共样本。"},
    ],
    choices:[
      {id:"publish-ash-protocol",label:"公开三方取证流程",hint:"证物可信度提高；敌军中仍相信程序的骑士会降低信念。",effects:{setFlags:["recovered_ash_testimony"],statChanges:{publicFaith:-2,goddessTrust:1}},next:"aftermath-choice"},
      {id:"protect-witness-names",label:"公开结论但隐去见证人姓名",hint:"降低报复风险，但之后需要再次证明证言来源。",effects:{setFlags:["protected_ash_witnesses"],statChanges:{civilianSafety:8}},next:"aftermath-choice"},
    ],
  },
  "odric-gatewatch":{
    id:"odric-gatewatch",kind:"dialogue",title:"骑士长守住的不是神",focusCharacterId:"odric",
    lines:[
      {text:"城门内侧堆着被踩碎的篮子和一只儿童木鞋。奥德里克没有站在最显眼的台阶上，而是在闸绳旁亲自清点每一队撤入巷道的人。他的银甲沾满烟灰，胸前女神徽记被布条遮住，只露出属于骑士长的旧伤。"},
      {speakerId:"odric",emotion:"resolve",text:"二十年前西门开过一次。城外的人想进来，城里的人想出去，谣言说井水有毒。没有敌军，没有神罚，只有两千个人在一条门洞里同时认为自己必须先走。我的母亲死在那下面。"},
      {speakerId:"the_unflagged",text:"所以你相信封门，不是因为女神命令，而是因为你见过恐慌如何杀人。可今天这道门也拦着守灯人的证词、祭坛样本和被提前写成凶手的蕾娜。"},
      {speakerId:"odric",emotion:"anger",text:"证据不会在踩踏里呼吸，孩子会。你们把机关抬到街上，守旧派会说亵渎，受害者会说复仇，卫道士会说进军。等他们开始互砍，写得最清楚的卷宗也挡不住一把刀。"},
      {speakerId:"seraphina",emotion:"resolve",text:"秩序不能只是让所有人按你安排的顺序沉默。我在祭坛上说了十八年“女神会回答”，今天我愿意当众说她没有给我答案。你至少要允许城里的人知道，接下来维持的是人的秩序。"},
      {speakerId:"odric",emotion:"doubt",text:"我从不信那团火会回答。可四万人每天醒来，面包按钟声出炉，城门按仪式开启，死者按同一段祷词下葬。你们称它谎言时，也要告诉我明早用什么让四万人继续起床。"},
      {speakerId:"reina",text:"用供水、粮账、能被质疑的命令。铁砧堡也把“理性”写成不许质疑的口号，所以我知道制度换一个词并不会自动变好。我们不是要一夜拆掉城市，只要求你别让城市吞掉证据。"},
      {text:"一名受伤的年轻骑士被同伴抬来。他正是刚才为灰烬封条作证的人。副官要求以泄露军令罪扣押他。奥德里克看向城门外骚动的人群，又看向那枚还没干透的骑士蜡印。"},
      {speakerId:"odric",emotion:"doubt",text:"如果我放他走，所有人会知道命令可以被违抗；如果我扣下他，所有人也会知道证词只在不触犯命令时才有效。秩序最危险的时候，是它开始只保护自己。"},
    ],
    choices:[
      {id:"ask-odric-spare-witness",label:"要求奥德里克亲自护送骑士见证人",hint:"迫使秩序保护一名违抗命令的人；Boss初始信念降低。",effects:{setFlags:["odric_spared_witness"],statChanges:{goddessTrust:1,publicFaith:-1}},next:"odric-approach"},
      {id:"exchange-copy-for-witness",label:"交出一份证据副本换取见证人通行",hint:"奥德里克保留程序控制，但公开承认证据不能消失。",effects:{setFlags:["odric_took_public_copy"],statChanges:{goddessTrust:2,wardenTrust:-1}},next:"odric-approach"},
    ],
  },
  "odric-lowered-sword":{
    id:"odric-lowered-sword",kind:"dialogue",title:"只够一人通过的门",focusCharacterId:"odric",
    lines:[
      {text:"盾阵被击破后，奥德里克仍握着剑，却把剑尖压到石缝里。他身后的副官等待新的封锁命令，城外的朝圣者等待门开，证据箱的铜角在地面留下长长一道划痕。没有人欢呼，因为所有人都知道让路不是认输的同义词。"},
      {speakerId:"odric",emotion:"doubt",text:"你们证明了这次熄火被人操纵，没证明女神从未存在；证明了命令提前写好，没证明开门不会死人。我可以让证据出去，却不能把整座城交给一句“以后再决定”。"},
      {speakerId:"the_unflagged",text:"那就不要交给一句话。把门开到只够见证人、伤员和证物通过；把人数、时刻和责任写下来；让你的骑士与广场选出的平民共同核对。秩序可以缩小自己的权力，而不是只能完整存在或彻底崩塌。"},
      {speakerId:"odric",emotion:"resolve",text:"我会签下这道临时令，也会在令尾写明：如果门外军队借机推进，我亲自关闭它；如果城内骑士销毁证据，我亲自逮捕他们。两边都会说我背叛，说明这份命令至少没有只讨好一边。"},
      {speakerId:"seraphina",text:"我会以塞拉菲娜的名字作证，不用圣女印。那枚印来自一套正在被检验的制度，我不能让它替我的眼睛增加重量。"},
      {speakerId:"reina",emotion:"doubt",text:"我会把装置图交给公开记录，也会注明哪些部分仍无法解释。卫道士若把空白写成“女神不存在”，他们和替神补写命令的人没有区别。"},
      {text:"奥德里克拔出压在石缝里的剑，用剑柄敲响门闩。门只升起一人高，第一批通过的不是使团，而是两名抬着担架的圣辉民兵。第二批是守灯人和年轻骑士。证据箱最后通过，确保任何一方都不能拿它当先行旗帜。"},
      {speakerId:"odric",emotion:"resolve",text:"别把我写成被真相击败的人。我只是看见一种比封死城门更精确的秩序。如果它失败，我仍会挡在这里；如果它成功，明天的城门就不必再靠一个骑士长的判断。"},
      {text:"门外，一月王国的海鸟从云层下掠过，没有落下任何旗。你知道这一章没有回答女神是否存在，只让几个原本能替她或替理性发号施令的人，第一次把自己的名字写在决定下面。"},
    ],
    choices:[
      {id:"odric-publish-record",label:"让临时通行令与全部证物同时公开",hint:"公开路线继承此前证据与见证，进入真相结局。",condition:{flagsAll:["revealed_mechanism"]},effects:{setFlags:["odric_signed_passage"],statChanges:{publicFaith:-3,civilianSafety:5}},next:"truth-ending"},
      {id:"odric-seal-record",label:"让通行令先执行，证物交三方封存",hint:"秩序路线保留公开日期与共同保管人。",condition:{flagsAll:["concealed_mechanism"]},effects:{setFlags:["odric_signed_passage"],statChanges:{civilianSafety:8,goddessTrust:1}},next:"order-ending"},
      {id:"odric-setback-record",label:"以幸存者证言启动公开听证",hint:"即使广场失守，也不让证言退回密室。",condition:{flagsNone:["revealed_mechanism","concealed_mechanism"]},effects:{setFlags:["odric_signed_passage"],statChanges:{civilianSafety:3}},next:"truth-ending"},
    ],
  },
};
