import type {DialogueNode} from "./types";

export const ironRoadExpansionNodes:Record<string,DialogueNode>={
  "reina-forge-child":{
    id:"reina-forge-child",kind:"dialogue",title:"养女与第七码头",focusCharacterId:"reina",
    lines:[
      {text:"雨停前，使团借宿在废弃的第七码头。蕾娜认出梁柱上的铆钉编号，那是赫尔曼还做矿工时带领工友修建的第一座装卸台。她小时候曾在这里等养父下工，用废铁拼出一辆能走三步的小车。"},
      {speakerId:"reina",emotion:"doubt",text:"赫尔曼捡到我时，我连自己的姓都不知道。他教我识图、算承重、在矿井塌方前听出支柱的声音。他也教我一件更危险的事：只要结果能救更多人，少数人的损失就可以写进预算。"},
      {speakerId:"the_unflagged",text:"你主张建立能离开铁砧堡的远征军。对老派将军而言，你是想让军队保护墙外的人；对河湾村民而言，一支能离堡的军队首先是一支会走到他们田里的军队。"},
      {speakerId:"reina",emotion:"anger",text:"我厌恶他们把所有新方案都叫冒险，却没有认真问过自己的固守让谁挨饿。可我也知道，机器一旦能走得更远，命令它前进的人未必还是我。铁砧堡把“可验证”当成道德证明，仿佛精确的炮程会让开火变得正确。"},
      {text:"码头仓壁上还留着旧日配给表。赫尔曼当矿工领班时，把自己的份额划给受伤者；成为议长后，他批准的边境预算却允许封路机碾过未登记村落。两份文件都盖着他的手印，无法用“他变坏了”解释完毕。"},
      {speakerId:"seraphina",text:"信仰里也有这种诱惑。一个人曾经救过别人，后来的人便把他的每句话都当成不会错。你若只揭露赫尔曼后来的命令，也可能抹掉人们为何愿意相信他。"},
      {speakerId:"reina",emotion:"resolve",text:"所以我要带回完整记录：他救过谁，也让谁从地图上消失；我设计过哪些安全阀，也主张过怎样的远征。不是为了平均功过，而是让每项决定都有作者，不能躲在“理性必然如此”后面。"},
      {speakerId:"the_unflagged",text:"完整记录会减慢开路，先救粮车会失去部分采购链。你已经作了选择，但仍可以决定如何承担另一边的代价：把技术交给村民，或把补给交给记录员，别让任何路线假装没有牺牲。"},
      {text:"蕾娜拆下童年小车上唯一还能转动的轮子，放进证据箱旁边。它不证明她有罪或无罪，只提醒她：每一台庞大机器最初都可能来自一个孩子想让某样东西向前走的愿望。"},
    ],
    choices:[
      {id:"reina-share-safety-diagram",label:"把封路机安全阀图交给河湾领路人",hint:"村民可辨认装置盲区；铁砧战场敌军移动降低。",condition:{flagsAll:["trusted_reina_plan"]},effects:{setFlags:["reina_disclosed_design"],statChanges:{wardenTrust:-1,civilianSafety:4}},next:"ledger-consequence"},
      {id:"reina-record-civilian-map",label:"把未登记村落补入军用地图",hint:"粮路路线保全更多平民，蕾娜承担篡改军图责任。",condition:{flagsAll:["protected_grain_route"]},effects:{setFlags:["reina_mapped_villages"],statChanges:{civilianSafety:6,wardenTrust:-1}},next:"road-consequence"},
    ],
  },
  "cole-granary-drill":{
    id:"cole-granary-drill",kind:"dialogue",title:"科尔教农民如何不成为军队",focusCharacterId:"cole",
    lines:[
      {text:"在通往灌渠的谷仓前，科尔让二十名河湾民兵放下崭新的长弓，先学会把粮袋从着火的仓门传到河边。年轻人不满：他们报名是为了保卫家园，不是继续搬运自己每天都在搬的东西。"},
      {speakerId:"cole",emotion:"resolve",text:"我年轻时在帝国残领服役，军官第一天教我们如何列队，最后一天才说撤退时别踩死自己人。等我明白顺序错了，已经有一半同伴埋在一条没人记得名字的坡上。"},
      {speakerId:"reina",text:"长弓手若不练射击，封路机不会因为他们会搬粮就停下。铁砧的斥候会测试这条路，发现软弱就会继续推进。"},
      {speakerId:"cole",emotion:"anger",text:"我不是教他们软弱。我在教他们先说清楚守什么。守粮仓，就把火扑灭、把人带走、把敌人赶出射程；若追到下一座村庄、拿走别人的粮补充自己，那就不再是防卫，只是换一面旗开始征用。"},
      {text:"他把谷仓、堤坝、渡口画成三个圆，要求民兵只在圆内预设射位。每个射位旁同时标出平民撤离线。有人问敌人逃出圆后怎么办，科尔回答“让他逃”，队伍里立刻响起不服气的低语。"},
      {speakerId:"cole",emotion:"doubt",text:"河湾人总说女神不种地、理性不打鱼，好像不参加争论就不会被战争找到。可只学会打仗也会让战争住下来。我的工作不是把农民变成士兵，是让他们有能力在危险过去后仍然变回农民。"},
      {speakerId:"the_unflagged",text:"这套规则会放走携带情报的斥候，也会避免一支临时民兵因为第一次胜利就追进邻境。我们可以让弓手守住三个圆，使团负责追查证据；代价是战斗中不能期待他们替我们完成进攻。"},
      {text:"一个十六岁的渔家女孩举手，说她父亲的船被双方军队征用过三次，每一次都说只是暂借。她愿意守渡口，但拒绝把弓带到别人家门前。科尔让她成为第一队队长，不因为她射得最准，而因为她最清楚界线为何存在。"},
      {speakerId:"cole",emotion:"resolve",text:"记住，能打赢的人最容易相信下一场也该由自己决定。等你们把粮袋搬完，我们练三轮齐射；每射一轮，队长都要先指出身后的撤离线。活着回家不是怯懦，是这支民兵成立的目的。"},
    ],
    choices:[
      {id:"cole-train-defense-circles",label:"采用科尔的三圈防卫规则",hint:"民兵守住补给与撤离线；我方在粮路战斗获得机动准备。",effects:{setFlags:["cole_trained_militia"],statChanges:{civilianSafety:7}},next:"blockade-approach"},
      {id:"cole-send-scout-pairs",label:"让科尔带双人斥候确认三处盲区",hint:"不扩大战线，提前揭示封路机部署。",effects:{setFlags:["cole_scouted_blindspots"],statChanges:{wardenTrust:1}},next:"blockade-approach"},
    ],
  },
  "wrench-provenance":{
    id:"wrench-provenance",kind:"dialogue",title:"折断扳手的两段旅程",evidenceRecovery:true,
    lines:[
      {text:"第一台封路机停下后，科尔从履带泥里找出半枚工坊检验章。它与圣辉祭坛旁的折断扳手严丝合缝，却比扳手上的磨痕新。蕾娜把两件东西并排放在车板上，请三个不同工坊的流动匠人逐一辨认。"},
      {speakerId:"reina",text:"扳手本体是铁砧旧制，十年前就停止发给正规工程兵。新检验章属于一家给军工总监瓦尔特供货的民营工坊。有人回收旧工具、重新盖章，再把它送进圣辉城当成“卫道士现役证物”。"},
      {speakerId:"cole",text:"河湾码头常见这种买卖。商人把旧船钉磨亮，当新货卖给两边；战争一来，旧货忽然有了政治身份。问题不是铁从哪里来，是谁安排它在最合适被发现的时候断在那里。"},
      {speakerId:"seraphina",emotion:"doubt",text:"如果公开这条链，圣辉城会说铁砧堡承认参与；铁砧堡会说民营工坊不代表军领。每个人都能在记录里找到一扇逃走的门。"},
      {speakerId:"the_unflagged",text:"那就不先宣布凶手。记录两段可验证的旅程：旧制扳手从正规库存退役，新检验章从供货工坊流出；再记录我们不知道中间由谁转手。承认缺口，反而让任何补上的名字都必须带来新证据。"},
      {text:"第一名匠人认出合金配比，第二名指出断口是人为预切，第三名在检验章边缘发现河湾盐仓使用的防潮油。三条意见彼此独立，说明扳手至少经过铁砧旧库、民营工坊与河湾转运点。"},
      {speakerId:"reina",emotion:"anger",text:"这条线足够证明有人经营冲突，却不足以证明赫尔曼亲自下令。公开时必须把这句话放在最前面。我恨他批准壁垒，但不能因为愤怒把尚未证明的命令塞进他手里。"},
      {text:"你把断成两截的扳手分别交给蕾娜与河湾匠人封存，拓印则交给塞拉菲娜。任何一方若修改自己的那份，另外两份都会留下差异。证物从“嫁祸卫道士的线索”变成一条需要三方共同维护的流通记录。"},
      {speakerId:"cole",emotion:"resolve",text:"证据和粮食一样，只有一处仓库就会被控制价格。把它分开保管，会慢，会争吵，却能让一个夜里的火烧不掉全部记忆。"},
    ],
    choices:[
      {id:"publish-wrench-chain",label:"公开扳手的三段流通记录",hint:"削弱伪旗者信念，但各方都将追查自己的泄漏者。",effects:{setFlags:["recovered_wrench_provenance"],statChanges:{publicFaith:2,wardenTrust:-1}},next:"grain-approach"},
      {id:"seal-three-wrench-copies",label:"建立三方封存与公开核验日期",hint:"暂缓指控，提升后续证据链的抗毁性。",effects:{setFlags:["secured_wrench_copies"],statChanges:{goddessTrust:1,civilianSafety:3}},next:"grain-approach"},
    ],
  },
  "cole-no-pursuit":{
    id:"cole-no-pursuit",kind:"dialogue",title:"胜利停在田埂上",focusCharacterId:"cole",
    lines:[
      {text:"粮车岔路的敌人撤向北岸时，河湾民兵第一次在真正的战斗里保持了阵线。年轻弓手追到田埂边，眼看再跑几十步就能夺下对方遗落的旗。科尔横过长弓，挡住自己刚教会射击的人。"},
      {speakerId:"cole",emotion:"resolve",text:"到这里。田埂这边是我们承诺保护的粮地，那边是另一个村的冬麦。跨过去追人，你们就会踩坏别人用来活命的东西，然后告诉自己这是胜利的必要代价。"},
      {speakerId:"reina",emotion:"anger",text:"那支斥候知道壁垒的部署。让他们回去，下一场敌人会准备得更好。战场不会因为我们画了一条道德边界就停止利用它。"},
      {speakerId:"cole",text:"所以使团可以派不会征粮、不会举旗的两个人跟踪；民兵必须留下。一个村庄能承受守卫家园的代价，承受不起把整个劳动力变成追击队。防卫若没有停止条件，早晚会需要税、军械和新的敌人来证明自己存在。"},
      {text:"渔家女孩放下已经搭箭的弓。她说敌人抢过父亲的船，自己当然想追；但渡口还有三名伤员，粮车的车轴也裂了。其他人沉默地转身搬运伤员，那面遗落的伪旗留在泥里，没有被当成战利品举起。"},
      {speakerId:"the_unflagged",text:"无旗不是没有力量，而是拒绝让一次胜利自动产生统治权。我们追查斥候只为确认壁垒位置，不替河湾宣布越境，也不把沿途补给视作可以征用。"},
      {speakerId:"cole",emotion:"doubt",text:"我教他们打仗，是因为怕不会打的人被吞掉；我拦住他们，也是怕学会打的人开始寻找能吞下的东西。这两种恐惧每天都在争，我没有一条永远正确的军规。"},
      {speakerId:"seraphina",text:"至少你允许他们看见争论。圣辉城的问题不是有仪式，而是仪式把选择伪装成神早已完成的答案。你的界线明天可以被重新讨论，已经比不可质疑的命令更接近保护。"},
      {text:"科尔把伪旗拆成布条，分别绑在三辆需要修理的粮车上，作为“不得征用”的醒目标记。旗帜失去号召追击的用途，变成提醒所有武装绕开伤员与口粮的普通红布。"},
    ],
    choices:[
      {id:"honor-cole-stop-line",label:"命令民兵停止追击，修复粮车",hint:"保住粮路与伤员；Boss战前队伍状态改善。",effects:{setFlags:["cole_rejected_pursuit"],statChanges:{civilianSafety:8}},next:"rain-camp-council"},
      {id:"send-unflagged-shadow",label:"由无旗者与科尔双人跟踪斥候",hint:"不动员民兵，取得壁垒接近路线。",effects:{setFlags:["cole_shadowed_scouts"],statChanges:{wardenTrust:1}},next:"rain-camp-council"},
    ],
  },
  "rain-camp-council":{
    id:"rain-camp-council",kind:"dialogue",title:"雨棚下的战前议会",
    lines:[
      {text:"铁窗壁垒的轰鸣越来越近，使团在倒塌水门旁搭起雨棚。桌上没有军旗，只有粮车车夫画的泥路、蕾娜的动力图、塞拉菲娜整理的伤员名单和科尔标出的停止线。每份材料都要求一种不同的准备。"},
      {speakerId:"reina",text:"动力核心每九十息泄压一次。若给我半个时辰，我能把折断扳手改成锁轴楔，让第一阶段装甲提前暴露；代价是我们必须让壁垒继续向村庄靠近。"},
      {speakerId:"cole",text:"伤员已经两夜没睡。让他们休整，队伍能扛住解除限速后的冲撞；但工坊监军会利用时间封死东侧灌渠。没有一种准备能同时把时间给我们、又不给敌人。"},
      {speakerId:"seraphina",emotion:"resolve",text:"我可以带采购拓印去找壁垒里的普通驾驶员，承诺投降者的名字只进入见证名单，不进入清算名单。若有人接受，敌方信念会动摇；若谈判失败，他们也会知道我们掌握记录。"},
      {speakerId:"the_unflagged",text:"休整、调查、交涉都不是菜单上的同义按钮。休整改变谁能活过冲撞；调查改变装甲何时暴露；交涉改变驾驶员是否继续相信命令。我们只能把一项做到足够可靠。"},
      {text:"雨棚外，村民争论是否该把粮车当路障。科尔反对，因为粮食一旦烧毁，胜负都救不了冬天；蕾娜建议拆下车轮做拒马，战后还能装回。两人用一刻钟把争论变成可逆的方案。"},
      {speakerId:"reina",emotion:"doubt",text:"我曾经把“可逆”当成胆怯，觉得工程就该一劳永逸。可壁垒正是一劳永逸的边境答案：它只会继续向前，直到所有问题都被压成平地。今天我们做能拆回去的拒马。"},
      {speakerId:"cole",emotion:"resolve",text:"也做一条明确撤离线。打不过时先带走人和记录，不为证明勇敢把最后一车种粮烧在这里。只要还有人记得机器怎样被停下，失败也不是归零。"},
      {text:"你把选择写在三份纸上，由蕾娜、科尔和塞拉菲娜分别签名。战后不论结果如何，任何人都可以指出是谁主张了什么、牺牲了什么，而不能把代价推给抽象的国家、理性或神。"},
    ],
    choices:[
      {id:"camp-investigate-core",label:"调查：连夜制作锁轴楔",hint:"铁窗壁垒第一阶段生命与移动降低。",effects:{setFlags:["camp_investigated_core"],statChanges:{wardenTrust:-1}},next:"thirteenth-name-on-grain-cart"},
      {id:"camp-rest-wounded",label:"休整：优先治疗伤员与更换车轴",hint:"我方进入Boss战时获得额外生命。",effects:{setFlags:["camp_restored_party"],statChanges:{civilianSafety:5}},next:"thirteenth-name-on-grain-cart"},
      {id:"camp-negotiate-drivers",label:"交涉：向驾驶员公开采购拓印",hint:"敌方信念下降，但装甲保持完整。",effects:{setFlags:["camp_negotiated_drivers"],statChanges:{publicFaith:2}},next:"thirteenth-name-on-grain-cart"},
    ],
  },
  "reina-hermann-platform":{
    id:"reina-hermann-platform",kind:"dialogue",title:"停机平台上的父女",focusCharacterId:"reina",
    lines:[
      {text:"铁窗壁垒停机后，赫尔曼没有逃。他坐在裂开的驾驶平台边，用矿工时代的手势示意剩余人员关闭蒸汽阀。蕾娜爬上平台时，他先检查她有没有受伤，随后才看见她手里的九份采购单。"},
      {speakerId:"reina",emotion:"anger",text:"你把同一台机器写成九次紧急需要。议会以为自己在保卫九段边境，实际上是在给同一条利益链续命。你知道村庄没有登记，也知道粮车会被拦住。"},
      {text:"赫尔曼回答，边境每年都有冲突，工坊需要订单才能留住熟练工，军领需要壁垒才能避免骑士冲进矿山。他没有声称命令来自理性必然，也没有否认签字，只说自己选择了一个能让铁砧堡继续运转的坏办法。"},
      {speakerId:"reina",emotion:"doubt",text:"你曾教我，支柱发出第三次裂响就必须撤人，哪怕矿主命令继续挖。为什么换成国家，你反而觉得只要还没完全塌，就可以继续把人留在下面？"},
      {speakerId:"the_unflagged",text:"公开采购链会让工坊停工、工人失去收入，也会阻止下一台壁垒碾过村庄；以证据换停火能让粮车今晚通过，却保留原来的利益结构。两条路都必须把受影响的人写进决定。"},
      {speakerId:"cole",text:"河湾愿意购买农具和水门零件，不会承担全部军工转产成本。可如果铁砧堡只会造墙，它就只能不断寻找需要墙的地方。和平不是停止订单一天，而是让工人的手还有别的东西可做。"},
      {speakerId:"seraphina",text:"圣辉城也靠朝圣维持旅舍、工坊和粮市，所以很多人害怕真相不只是因为信仰。制度会把生计缠在解释权上。拆开它需要替普通人准备下一顿饭，而不只是宣布旧答案错误。"},
      {text:"赫尔曼把议长印放在平台上，允许蕾娜盖下停机令，却拒绝替她决定是否公开采购单。他说，若她要成为能离堡远征的将军，就必须先证明远征不是把自己的正确带到别人土地上。"},
      {speakerId:"reina",emotion:"resolve",text:"我不会用你的印证明我正确。我会把设计责任、采购受益者、转产计划和村民损失一起公开；如果议会因此撤掉我的席位，我至少不能再躲在“只是工程师”后面。机器服从图纸，图纸必须服从能被人质疑的选择。"},
      {text:"她把童年小车的旧轮放在停机台上。赫尔曼认出它，沉默很久，最终把自己的矿工手印按在“接受公开质询”一栏，而不是“承认全部指控”一栏。父女没有和解，但第一次在同一份文件上承认彼此仍有权反驳。"},
    ],
    choices:[
      {id:"reina-publish-with-transition",label:"公开采购链与军工转产清单",hint:"真相路线同时记录工人与村民代价，不把蕾娜写成无责揭露者。",condition:{flagsAll:["exposed_iron_profit"]},effects:{setFlags:["reina_owned_design"],statChanges:{wardenTrust:-2,publicFaith:3}},next:"iron-truth-ending"},
      {id:"reina-timebound-truce",label:"签署有期限的停机令与公开日期",hint:"秩序路线立即通粮，但证据必须在期限后进入听证。",condition:{flagsNone:["exposed_iron_profit"]},effects:{setFlags:["reina_owned_design"],statChanges:{civilianSafety:8,wardenTrust:1}},next:"iron-order-ending"},
    ],
  },
};
