import type { Character, Evidence, Faction } from "./types";

export const factions: Record<Faction["id"], Faction> = {
  goddess_state: {
    id: "goddess_state",
    name: "女神国",
    shortName: "圣辉",
    creed: "秩序来自共同相信之物。",
    color: "#d9c37a",
    description: "以圣辉城和女神信仰维系统治的神权国家。圣火既是宗教象征，也是政权合法性的核心。",
  },
  wardens: {
    id: "wardens",
    name: "卫道士军国",
    shortName: "铁砧",
    creed: "凡神迹，皆应接受检验。",
    color: "#8095a3",
    description: "崇尚理性、纪律与工程技术的军事国家，长期被女神国指控亵渎圣迹。",
  },
  new_kavala: {
    id: "new_kavala",
    name: "新卡瓦拉",
    shortName: "河湾",
    creed: "先让人活过冬天，再谈谁拥有真理。",
    color: "#748f61",
    description: "依靠农地、商路与自治城镇组成的务实联盟，最在意平民与粮路。",
  },
  unflagged: {
    id: "unflagged",
    name: "无旗使团",
    shortName: "无旗者",
    creed: "不替任何旗帜保管真相。",
    color: "#c7c9c8",
    description: "在诸国之间调查争端的小型中立使团，权力有限，但可以携带证据穿过边境。",
  },
  council: {
    id: "council",
    name: "议会国",
    shortName: "议会",
    creed: "权力必须被记录、质询与轮替。",
    color: "#a7b4bf",
    description: "由城邦议会与军需官共同维持的河湾联盟，擅长谈判与资源调度。",
  },
  black_church: {
    id: "black_church",
    name: "黑色教廷",
    shortName: "黑廷",
    creed: "信仰应当服从唯一的解释。",
    color: "#705c74",
    description: "从旧神学中分裂出的严苛教廷，擅长审查、传送与改写记忆。",
  },
};

export const characters: Record<Character["id"], Character> = {
  the_unflagged: {
    id: "the_unflagged",
    name: "无旗者",
    title: "中立调查使",
    factionId: "unflagged",
    role: "player",
    portraitKey: "unflagged",
    description: "受圆桌密约保护的调查者。没有军队，唯一的武器是各方暂时承认的中立身份。",
  },
  seraphina: {
    id: "seraphina",
    name: "塞拉菲娜",
    title: "候补圣女",
    factionId: "goddess_state",
    role: "companion",
    portraitKey: "seraphina",
    description: "相信信仰应当保护弱者，却第一次亲眼见到圣火熄灭。",
  },
  reina: {
    id: "reina",
    name: "蕾娜",
    title: "铁砧工程官",
    factionId: "wardens",
    role: "companion",
    portraitKey: "reina",
    description: "被扣留在圣辉城的卫道士工程官，认为所谓神迹必有可测量的结构。",
  },
  odric: {
    id: "odric",
    name: "奥德里克",
    title: "离职骑士长",
    factionId: "goddess_state",
    role: "companion",
    portraitKey: "odric",
    description: "曾替制度守门的女神骑士长，正在学习把具体的人放在抽象秩序之前。",
  },
  cole: {
    id: "cole",
    name: "科尔",
    title: "河湾老兵教官",
    factionId: "new_kavala",
    role: "companion",
    portraitKey: "cole",
    description: "只想让乡民有能力守住粮田，又害怕防卫最终长成另一面军旗。",
  },
  agnes: {
    id: "agnes",
    name: "阿格尼丝",
    title: "流亡抄经修女",
    factionId: "unflagged",
    role: "companion",
    portraitKey: "agnes",
    description: "从黑色教廷带出被删改的档案，相信记忆不应只属于审判者。",
  },
  old_mara: {
    id: "old_mara",
    name: "老玛拉",
    title: "守灯人",
    factionId: "goddess_state",
    role: "civilian",
    portraitKey: "old-mara",
    description: "三十年来负责补充圣火灯油，知道祭坛所有不该被谈论的细节。",
  },
  masked_saboteur: {
    id: "masked_saboteur",
    name: "灰眼人",
    title: "蒙面破坏者",
    factionId: "unflagged",
    role: "enemy",
    portraitKey: "masked-saboteur",
    description: "趁混乱潜入祭坛的人。他想要的不是熄灭圣火，而是让所有人看见圣火可以熄灭。",
  },
  arthur: {
    id: "arthur",
    name: "亚瑟",
    title: "刑场苏醒的见习士兵",
    factionId: "wardens",
    role: "player",
    portraitKey: "arthur",
    description: "在处刑台上醒来的异乡人，获得一套只对自己可见的战场系统。",
  },
  hans: {
    id: "hans",
    name: "汉斯",
    title: "卫道士盾手",
    factionId: "wardens",
    role: "companion",
    portraitKey: "hans",
    description: "把军纪当作护住同伴的最后一道墙，擅长格挡、拦截和维持阵线。",
  },
  asnoka: {
    id: "asnoka",
    name: "阿斯诺卡",
    title: "边境侦骑",
    factionId: "new_kavala",
    role: "companion",
    portraitKey: "asnoka",
    description: "熟悉边境粮路与林地水闸的侦骑，能在交战前找出一条不被看见的路。",
  },
  white_knight_captain: {
    id: "white_knight_captain",
    name: "白光骑士长",
    title: "女神国前线总监",
    factionId: "goddess_state",
    role: "enemy",
    portraitKey: "white-knight",
    description: "以纪律和盾阵检验新兵，把忠诚视为比生命更可靠的护甲。",
  },
  night_judge: {
    id: "night_judge",
    name: "永夜殿审判官",
    title: "黑色教廷内心审查官",
    factionId: "black_church",
    role: "enemy",
    portraitKey: "night-judge",
    description: "将政治关系变成审讯记录的审判官，能把犹豫变成可见的战场压力。",
  },
  lake_dual_god: {
    id: "lake_dual_god",
    name: "湖都双邪神",
    title: "信仰发散器的双重核心",
    factionId: "black_church",
    role: "enemy",
    portraitKey: "lake-dual-god",
    description: "彼此争夺同一具神力容器的双重意志，只有关闭发散器才能结束战斗。",
  },
};

export const evidence: Record<Evidence["id"], Evidence> = {
  lamp_oil_ledger: {
    id: "lamp_oil_ledger",
    name: "守灯账簿",
    summary: "圣火每七日消耗一桶精炼灯油。",
    detail: "账簿末页被撕去，但墨迹压痕显示本周灯油被一名陌生祭司提前领走。",
    iconKey: "ledger",
    tags: ["祭坛", "人工装置", "后勤"],
  },
  cold_ash: {
    id: "cold_ash",
    name: "无温余烬",
    summary: "祭坛灰烬完全冰冷，与众人声称的熄灭时间矛盾。",
    detail: "火焰至少在钟响前一小时已经熄灭；有人用幻光维持了圣火仍在燃烧的假象。",
    iconKey: "ash",
    tags: ["时间线", "幻光", "祭坛"],
  },
  broken_wrench: {
    id: "broken_wrench",
    name: "折断的异制扳手",
    summary: "一件看似卫道士工具的破坏器具。",
    detail: "尺寸采用铁砧制式，金属却来自本地工坊；这是为嫁祸而制造的仿品。",
    iconKey: "wrench",
    tags: ["嫁祸", "卫道士", "破坏"],
  },
};
